/* soapWsTopologyServiceSoapProxy.h
   Generated by gSOAP 2.7.15 from Services.h
   Copyright(C) 2000-2009, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef soapWsTopologyServiceSoapProxy_H
#define soapWsTopologyServiceSoapProxy_H
#include "soapH.h"

class SOAP_CMAC WsTopologyServiceSoapProxy : public soap
{ public:
	/// Endpoint URL of service 'WsTopologyServiceSoapProxy' (change as needed)
	const char *soap_endpoint;
	/// Constructor
	WsTopologyServiceSoapProxy();
	/// Constructor with copy of another engine state
	WsTopologyServiceSoapProxy(const struct soap&);
	/// Constructor with engine input+output mode control
	WsTopologyServiceSoapProxy(soap_mode iomode);
	/// Constructor with engine input and output mode control
	WsTopologyServiceSoapProxy(soap_mode imode, soap_mode omode);
	/// Destructor frees deserialized data
	virtual	~WsTopologyServiceSoapProxy();
	/// Initializer used by constructors
	virtual	void WsTopologyServiceSoapProxy_init(soap_mode imode, soap_mode omode);
	/// Delete all deserialized data (uses soap_destroy and soap_end)
	virtual	void destroy();
	/// Disables and removes SOAP Header from message
	virtual	void soap_noheader();
	/// Get SOAP Fault structure (NULL when absent)
	virtual	const SOAP_ENV__Fault *soap_fault();
	/// Get SOAP Fault string (NULL when absent)
	virtual	const char *soap_fault_string();
	/// Get SOAP Fault detail as string (NULL when absent)
	virtual	const char *soap_fault_detail();
	/// Force close connection (normally automatic, except for send_X ops)
	virtual	int soap_close_socket();
	/// Print fault
	virtual	void soap_print_fault(FILE*);
#ifndef WITH_LEAN
	/// Print fault to stream
	virtual	void soap_stream_fault(std::ostream&);
	/// Put fault into buffer
	virtual	char *soap_sprint_fault(char *buf, size_t len);
#endif

	/// Web service operation 'SystemLog' (returns error code or SOAP_OK)
	virtual	int SystemLog(_ns5__SystemLogRequest *ns5__SystemLogRequest, _ns5__SystemLogResponse *ns5__SystemLogResponse);

	/// Web service operation 'TpClusterInfo' (returns error code or SOAP_OK)
	virtual	int TpClusterInfo(_ns5__TpClusterInfoRequest *ns5__TpClusterInfoRequest, _ns5__TpClusterInfoResponse *ns5__TpClusterInfoResponse);

	/// Web service operation 'TpClusterQuery' (returns error code or SOAP_OK)
	virtual	int TpClusterQuery(_ns5__TpClusterQueryRequest *ns5__TpClusterQueryRequest, _ns5__TpClusterQueryResponse *ns5__TpClusterQueryResponse);

	/// Web service operation 'TpDropZoneQuery' (returns error code or SOAP_OK)
	virtual	int TpDropZoneQuery(_ns5__TpDropZoneQueryRequest *ns5__TpDropZoneQueryRequest, _ns5__TpDropZoneQueryResponse *ns5__TpDropZoneQueryResponse);

	/// Web service operation 'TpGetComponentFile' (returns error code or SOAP_OK)
	virtual	int TpGetComponentFile(_ns5__TpGetComponentFileRequest *ns5__TpGetComponentFileRequest, _ns5__TpGetComponentFileResponse *ns5__TpGetComponentFileResponse);

	/// Web service operation 'TpGetServicePlugins' (returns error code or SOAP_OK)
	virtual	int TpGetServicePlugins(_ns5__TpGetServicePluginsRequest *ns5__TpGetServicePluginsRequest, _ns5__TpGetServicePluginsResponse *ns5__TpGetServicePluginsResponse);

	/// Web service operation 'TpGroupQuery' (returns error code or SOAP_OK)
	virtual	int TpGroupQuery(_ns5__TpGroupQueryRequest *ns5__TpGroupQueryRequest, _ns5__TpGroupQueryResponse *ns5__TpGroupQueryResponse);

	/// Web service operation 'TpListTargetClusters' (returns error code or SOAP_OK)
	virtual	int TpListTargetClusters(_ns5__TpListTargetClustersRequest *ns5__TpListTargetClustersRequest, _ns5__TpListTargetClustersResponse *ns5__TpListTargetClustersResponse);

	/// Web service operation 'TpLogFile' (returns error code or SOAP_OK)
	virtual	int TpLogFile(_ns5__TpLogFileRequest *ns5__TpLogFileRequest, _ns5__TpLogFileResponse *ns5__TpLogFileResponse);

	/// Web service operation 'TpLogFileDisplay' (returns error code or SOAP_OK)
	virtual	int TpLogFileDisplay(_ns5__TpLogFileRequest *ns5__TpLogFileRequest, _ns5__TpLogFileResponse *ns5__TpLogFileResponse);

	/// Web service operation 'TpLogicalClusterQuery' (returns error code or SOAP_OK)
	virtual	int TpLogicalClusterQuery(_ns5__TpLogicalClusterQueryRequest *ns5__TpLogicalClusterQueryRequest, _ns5__TpLogicalClusterQueryResponse *ns5__TpLogicalClusterQueryResponse);

	/// Web service operation 'TpMachineInfo' (returns error code or SOAP_OK)
	virtual	int TpMachineInfo(_ns5__TpMachineInfoRequest *ns5__TpMachineInfoRequest, _ns5__TpMachineInfoResponse *ns5__TpMachineInfoResponse);

	/// Web service operation 'TpMachineQuery' (returns error code or SOAP_OK)
	virtual	int TpMachineQuery(_ns5__TpMachineQueryRequest *ns5__TpMachineQueryRequest, _ns5__TpMachineQueryResponse *ns5__TpMachineQueryResponse);

	/// Web service operation 'TpServiceQuery' (returns error code or SOAP_OK)
	virtual	int TpServiceQuery(_ns5__TpServiceQueryRequest *ns5__TpServiceQueryRequest, _ns5__TpServiceQueryResponse *ns5__TpServiceQueryResponse);

	/// Web service operation 'TpSetMachineStatus' (returns error code or SOAP_OK)
	virtual	int TpSetMachineStatus(_ns5__TpSetMachineStatusRequest *ns5__TpSetMachineStatusRequest, _ns5__TpSetMachineStatusResponse *ns5__TpSetMachineStatusResponse);

	/// Web service operation 'TpSwapNode' (returns error code or SOAP_OK)
	virtual	int TpSwapNode(_ns5__TpSwapNodeRequest *ns5__TpSwapNodeRequest, _ns5__TpSwapNodeResponse *ns5__TpSwapNodeResponse);

	/// Web service operation 'TpTargetClusterQuery' (returns error code or SOAP_OK)
	virtual	int TpTargetClusterQuery(_ns5__TpTargetClusterQueryRequest *ns5__TpTargetClusterQueryRequest, _ns5__TpTargetClusterQueryResponse *ns5__TpTargetClusterQueryResponse);

	/// Web service operation 'TpThorStatus' (returns error code or SOAP_OK)
	virtual	int TpThorStatus(_ns5__TpThorStatusRequest *ns5__TpThorStatusRequest, _ns5__TpThorStatusResponse *ns5__TpThorStatusResponse);

	/// Web service operation 'TpXMLFile' (returns error code or SOAP_OK)
	virtual	int TpXMLFile(_ns5__TpXMLFileRequest *ns5__TpXMLFileRequest, _ns5__TpXMLFileResponse *ns5__TpXMLFileResponse);
};
#endif
