/* soapWsWorkunitsServiceSoapProxy.h
   Generated by gSOAP 2.7.15 from Services.h
   Copyright(C) 2000-2009, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef soapWsWorkunitsServiceSoapProxy_H
#define soapWsWorkunitsServiceSoapProxy_H
#include "soapH.h"

class SOAP_CMAC WsWorkunitsServiceSoapProxy : public soap
{ public:
	/// Endpoint URL of service 'WsWorkunitsServiceSoapProxy' (change as needed)
	const char *soap_endpoint;
	/// Constructor
	WsWorkunitsServiceSoapProxy();
	/// Constructor with copy of another engine state
	WsWorkunitsServiceSoapProxy(const struct soap&);
	/// Constructor with engine input+output mode control
	WsWorkunitsServiceSoapProxy(soap_mode iomode);
	/// Constructor with engine input and output mode control
	WsWorkunitsServiceSoapProxy(soap_mode imode, soap_mode omode);
	/// Destructor frees deserialized data
	virtual	~WsWorkunitsServiceSoapProxy();
	/// Initializer used by constructors
	virtual	void WsWorkunitsServiceSoapProxy_init(soap_mode imode, soap_mode omode);
	/// Delete all deserialized data (uses soap_destroy and soap_end)
	virtual	void destroy();
	/// Disables and removes SOAP Header from message
	virtual	void soap_noheader();
	/// Get SOAP Fault structure (NULL when absent)
	virtual	const SOAP_ENV__Fault *soap_fault();
	/// Get SOAP Fault string (NULL when absent)
	virtual	const char *soap_fault_string();
	/// Get SOAP Fault detail as string (NULL when absent)
	virtual	const char *soap_fault_detail();
	/// Force close connection (normally automatic, except for send_X ops)
	virtual	int soap_close_socket();
	/// Print fault
	virtual	void soap_print_fault(FILE*);
#ifndef WITH_LEAN
	/// Print fault to stream
	virtual	void soap_stream_fault(std::ostream&);
	/// Put fault into buffer
	virtual	char *soap_sprint_fault(char *buf, size_t len);
#endif

	/// Web service operation 'GVCAjaxGraph' (returns error code or SOAP_OK)
	virtual	int GVCAjaxGraph(_ns6__GVCAjaxGraph *ns6__GVCAjaxGraph, _ns6__GVCAjaxGraphResponse *ns6__GVCAjaxGraphResponse);

	/// Web service operation 'WUAbort' (returns error code or SOAP_OK)
	virtual	int WUAbort(_ns6__WUAbort *ns6__WUAbort, _ns6__WUAbortResponse *ns6__WUAbortResponse);

	/// Web service operation 'WUAction' (returns error code or SOAP_OK)
	virtual	int WUAction(_ns6__WUAction *ns6__WUAction, _ns6__WUActionResponse *ns6__WUActionResponse);

	/// Web service operation 'WUAddLocalFileToWorkunit' (returns error code or SOAP_OK)
	virtual	int WUAddLocalFileToWorkunit(_ns6__WUAddLocalFileToWorkunit *ns6__WUAddLocalFileToWorkunit, _ns6__WUAddLocalFileToWorkunitResponse *ns6__WUAddLocalFileToWorkunitResponse);

	/// Web service operation 'WUCDebug' (returns error code or SOAP_OK)
	virtual	int WUCDebug(_ns6__WUCDebug *ns6__WUCDebug, _ns6__WUDebugResponse *ns6__WUDebugResponse);

	/// Web service operation 'WUCheckFeatures' (returns error code or SOAP_OK)
	virtual	int WUCheckFeatures(_ns6__WUCheckFeatures *ns6__WUCheckFeatures, _ns6__WUCheckFeaturesResponse *ns6__WUCheckFeaturesResponse);

	/// Web service operation 'WUClusterJobQueueLOG' (returns error code or SOAP_OK)
	virtual	int WUClusterJobQueueLOG(_ns6__WUClusterJobQueueLOG *ns6__WUClusterJobQueueLOG, _ns6__WUClusterJobQueueLOGResponse *ns6__WUClusterJobQueueLOGResponse);

	/// Web service operation 'WUClusterJobQueueXLS' (returns error code or SOAP_OK)
	virtual	int WUClusterJobQueueXLS(_ns6__WUClusterJobQueueXLS *ns6__WUClusterJobQueueXLS, _ns6__WUClusterJobQueueXLSResponse *ns6__WUClusterJobQueueXLSResponse);

	/// Web service operation 'WUClusterJobSummaryXLS' (returns error code or SOAP_OK)
	virtual	int WUClusterJobSummaryXLS(_ns6__WUClusterJobSummaryXLS *ns6__WUClusterJobSummaryXLS, _ns6__WUClusterJobSummaryXLSResponse *ns6__WUClusterJobSummaryXLSResponse);

	/// Web service operation 'WUClusterJobXLS' (returns error code or SOAP_OK)
	virtual	int WUClusterJobXLS(_ns6__WUClusterJobXLS *ns6__WUClusterJobXLS, _ns6__WUClusterJobXLSResponse *ns6__WUClusterJobXLSResponse);

	/// Web service operation 'WUCompileECL' (returns error code or SOAP_OK)
	virtual	int WUCompileECL(_ns6__WUCompileECL *ns6__WUCompileECL, _ns6__WUCompileECLResponse *ns6__WUCompileECLResponse);

	/// Web service operation 'WUCopyLogicalFiles' (returns error code or SOAP_OK)
	virtual	int WUCopyLogicalFiles(_ns6__WUCopyLogicalFiles *ns6__WUCopyLogicalFiles, _ns6__WUCopyLogicalFilesResponse *ns6__WUCopyLogicalFilesResponse);

	/// Web service operation 'WUCopyQuerySet' (returns error code or SOAP_OK)
	virtual	int WUCopyQuerySet(_ns6__WUCopyQuerySet *ns6__WUCopyQuerySet, _ns6__WUCopyQuerySetResponse *ns6__WUCopyQuerySetResponse);

	/// Web service operation 'WUCreate' (returns error code or SOAP_OK)
	virtual	int WUCreate(_ns6__WUCreate *ns6__WUCreate, _ns6__WUCreateResponse *ns6__WUCreateResponse);

	/// Web service operation 'WUCreateAndUpdate' (returns error code or SOAP_OK)
	virtual	int WUCreateAndUpdate(_ns6__WUCreateAndUpdate *ns6__WUCreateAndUpdate, _ns6__WUUpdateResponse *ns6__WUUpdateResponse);

	/// Web service operation 'WUCreateZAPInfo' (returns error code or SOAP_OK)
	virtual	int WUCreateZAPInfo(_ns6__WUCreateZAPInfo *ns6__WUCreateZAPInfo, _ns6__WUCreateZAPInfoResponse *ns6__WUCreateZAPInfoResponse);

	/// Web service operation 'WUDelete' (returns error code or SOAP_OK)
	virtual	int WUDelete(_ns6__WUDelete *ns6__WUDelete, _ns6__WUDeleteResponse *ns6__WUDeleteResponse);

	/// Web service operation 'WUDeployWorkunit' (returns error code or SOAP_OK)
	virtual	int WUDeployWorkunit(_ns6__WUDeployWorkunit *ns6__WUDeployWorkunit, _ns6__WUDeployWorkunitResponse *ns6__WUDeployWorkunitResponse);

	/// Web service operation 'WUExport' (returns error code or SOAP_OK)
	virtual	int WUExport(_ns6__WUExport *ns6__WUExport, _ns6__WUExportResponse *ns6__WUExportResponse);

	/// Web service operation 'WUFile' (returns error code or SOAP_OK)
	virtual	int WUFile(_ns6__WUFile *ns6__WUFile, _ns6__WULogFileResponse *ns6__WULogFileResponse);

	/// Web service operation 'WUFullResult' (returns error code or SOAP_OK)
	virtual	int WUFullResult(_ns6__WUFullResult *ns6__WUFullResult, _ns6__WUFullResultResponse *ns6__WUFullResultResponse);

	/// Web service operation 'WUGVCGraphInfo' (returns error code or SOAP_OK)
	virtual	int WUGVCGraphInfo(_ns6__WUGVCGraphInfo *ns6__WUGVCGraphInfo, _ns6__WUGVCGraphInfoResponse *ns6__WUGVCGraphInfoResponse);

	/// Web service operation 'WUGetArchiveFile' (returns error code or SOAP_OK)
	virtual	int WUGetArchiveFile(_ns6__WUGetArchiveFile *ns6__WUGetArchiveFile, _ns6__WUGetArchiveFileResponse *ns6__WUGetArchiveFileResponse);

	/// Web service operation 'WUGetDependancyTrees' (returns error code or SOAP_OK)
	virtual	int WUGetDependancyTrees(_ns6__WUGetDependancyTrees *ns6__WUGetDependancyTrees, _ns6__WUGetDependancyTreesResponse *ns6__WUGetDependancyTreesResponse);

	/// Web service operation 'WUGetGraph' (returns error code or SOAP_OK)
	virtual	int WUGetGraph(_ns6__WUGetGraph *ns6__WUGetGraph, _ns6__WUGetGraphResponse *ns6__WUGetGraphResponse);

	/// Web service operation 'WUGetGraphNameAndTypes' (returns error code or SOAP_OK)
	virtual	int WUGetGraphNameAndTypes(_ns6__WUGetGraphNameAndTypes *ns6__WUGetGraphNameAndTypes, _ns6__WUGetGraphNameAndTypesResponse *ns6__WUGetGraphNameAndTypesResponse);

	/// Web service operation 'WUGetNumFileToCopy' (returns error code or SOAP_OK)
	virtual	int WUGetNumFileToCopy(_ns6__WUGetNumFileToCopy *ns6__WUGetNumFileToCopy, _ns6__WUGetNumFileToCopyResponse *ns6__WUGetNumFileToCopyResponse);

	/// Web service operation 'WUGetStats' (returns error code or SOAP_OK)
	virtual	int WUGetStats(_ns6__WUGetStats *ns6__WUGetStats, _ns6__WUGetStatsResponse *ns6__WUGetStatsResponse);

	/// Web service operation 'WUGetZAPInfo' (returns error code or SOAP_OK)
	virtual	int WUGetZAPInfo(_ns6__WUGetZAPInfo *ns6__WUGetZAPInfo, _ns6__WUGetZAPInfoResponse *ns6__WUGetZAPInfoResponse);

	/// Web service operation 'WUGraphInfo' (returns error code or SOAP_OK)
	virtual	int WUGraphInfo(_ns6__WUGraphInfo *ns6__WUGraphInfo, _ns6__WUGraphInfoResponse *ns6__WUGraphInfoResponse);

	/// Web service operation 'WUGraphTiming' (returns error code or SOAP_OK)
	virtual	int WUGraphTiming(_ns6__WUGraphTiming *ns6__WUGraphTiming, _ns6__WUGraphTimingResponse *ns6__WUGraphTimingResponse);

	/// Web service operation 'WUInfo' (returns error code or SOAP_OK)
	virtual	int WUInfo(_ns6__WUInfo *ns6__WUInfo, _ns6__WUInfoResponse *ns6__WUInfoResponse);

	/// Web service operation 'WUInfoDetails' (returns error code or SOAP_OK)
	virtual	int WUInfoDetails(_ns6__WUInfoDetails *ns6__WUInfoDetails, _ns6__WUInfoResponse *ns6__WUInfoResponse);

	/// Web service operation 'WUJobList' (returns error code or SOAP_OK)
	virtual	int WUJobList(_ns6__WUJobList *ns6__WUJobList, _ns6__WUJobListResponse *ns6__WUJobListResponse);

	/// Web service operation 'WULightWeightQuery' (returns error code or SOAP_OK)
	virtual	int WULightWeightQuery(_ns6__WULightWeightQuery *ns6__WULightWeightQuery, _ns6__WULightWeightQueryResponse *ns6__WULightWeightQueryResponse);

	/// Web service operation 'WUListArchiveFiles' (returns error code or SOAP_OK)
	virtual	int WUListArchiveFiles(_ns6__WUListArchiveFiles *ns6__WUListArchiveFiles, _ns6__WUListArchiveFilesResponse *ns6__WUListArchiveFilesResponse);

	/// Web service operation 'WUListLocalFileRequired' (returns error code or SOAP_OK)
	virtual	int WUListLocalFileRequired(_ns6__WUListLocalFileRequired *ns6__WUListLocalFileRequired, _ns6__WUListLocalFileRequiredResponse *ns6__WUListLocalFileRequiredResponse);

	/// Web service operation 'WUListQueries' (returns error code or SOAP_OK)
	virtual	int WUListQueries(_ns6__WUListQueries *ns6__WUListQueries, _ns6__WUListQueriesResponse *ns6__WUListQueriesResponse);

	/// Web service operation 'WUListQueriesUsingFile' (returns error code or SOAP_OK)
	virtual	int WUListQueriesUsingFile(_ns6__WUListQueriesUsingFile *ns6__WUListQueriesUsingFile, _ns6__WUListQueriesUsingFileResponse *ns6__WUListQueriesUsingFileResponse);

	/// Web service operation 'WUMultiQuerysetDetails' (returns error code or SOAP_OK)
	virtual	int WUMultiQuerysetDetails(_ns6__WUMultiQuerysetDetails *ns6__WUMultiQuerysetDetails, _ns6__WUMultiQuerySetDetailsResponse *ns6__WUMultiQuerySetDetailsResponse);

	/// Web service operation 'WUProcessGraph' (returns error code or SOAP_OK)
	virtual	int WUProcessGraph(_ns6__WUProcessGraph *ns6__WUProcessGraph, _ns6__WUProcessGraphResponse *ns6__WUProcessGraphResponse);

	/// Web service operation 'WUProtect' (returns error code or SOAP_OK)
	virtual	int WUProtect(_ns6__WUProtect *ns6__WUProtect, _ns6__WUProtectResponse *ns6__WUProtectResponse);

	/// Web service operation 'WUPublishWorkunit' (returns error code or SOAP_OK)
	virtual	int WUPublishWorkunit(_ns6__WUPublishWorkunit *ns6__WUPublishWorkunit, _ns6__WUPublishWorkunitResponse *ns6__WUPublishWorkunitResponse);

	/// Web service operation 'WUPushEvent' (returns error code or SOAP_OK)
	virtual	int WUPushEvent(_ns6__WUPushEvent *ns6__WUPushEvent, _ns6__WUPushEventResponse *ns6__WUPushEventResponse);

	/// Web service operation 'WUQuery' (returns error code or SOAP_OK)
	virtual	int WUQuery(_ns6__WUQuery *ns6__WUQuery, _ns6__WUQueryResponse *ns6__WUQueryResponse);

	/// Web service operation 'WUQueryConfig' (returns error code or SOAP_OK)
	virtual	int WUQueryConfig(_ns6__WUQueryConfig *ns6__WUQueryConfig, _ns6__WUQueryConfigResponse *ns6__WUQueryConfigResponse);

	/// Web service operation 'WUQueryDetails' (returns error code or SOAP_OK)
	virtual	int WUQueryDetails(_ns6__WUQueryDetails *ns6__WUQueryDetails, _ns6__WUQueryDetailsResponse *ns6__WUQueryDetailsResponse);

	/// Web service operation 'WUQueryFiles' (returns error code or SOAP_OK)
	virtual	int WUQueryFiles(_ns6__WUQueryFiles *ns6__WUQueryFiles, _ns6__WUQueryFilesResponse *ns6__WUQueryFilesResponse);

	/// Web service operation 'WUQueryGetGraph' (returns error code or SOAP_OK)
	virtual	int WUQueryGetGraph(_ns6__WUQueryGetGraph *ns6__WUQueryGetGraph, _ns6__WUQueryGetGraphResponse *ns6__WUQueryGetGraphResponse);

	/// Web service operation 'WUQuerysetAliasAction' (returns error code or SOAP_OK)
	virtual	int WUQuerysetAliasAction(_ns6__WUQuerysetAliasAction *ns6__WUQuerysetAliasAction, _ns6__WUQuerySetAliasActionResponse *ns6__WUQuerySetAliasActionResponse);

	/// Web service operation 'WUQuerysetCopyQuery' (returns error code or SOAP_OK)
	virtual	int WUQuerysetCopyQuery(_ns6__WUQuerysetCopyQuery *ns6__WUQuerysetCopyQuery, _ns6__WUQuerySetCopyQueryResponse *ns6__WUQuerySetCopyQueryResponse);

	/// Web service operation 'WUQuerysetDetails' (returns error code or SOAP_OK)
	virtual	int WUQuerysetDetails(_ns6__WUQuerysetDetails *ns6__WUQuerysetDetails, _ns6__WUQuerySetDetailsResponse *ns6__WUQuerySetDetailsResponse);

	/// Web service operation 'WUQuerysetQueryAction' (returns error code or SOAP_OK)
	virtual	int WUQuerysetQueryAction(_ns6__WUQuerysetQueryAction *ns6__WUQuerysetQueryAction, _ns6__WUQuerySetQueryActionResponse *ns6__WUQuerySetQueryActionResponse);

	/// Web service operation 'WUQuerysets' (returns error code or SOAP_OK)
	virtual	int WUQuerysets(_ns6__WUQuerysets *ns6__WUQuerysets, _ns6__WUQuerysetsResponse *ns6__WUQuerysetsResponse);

	/// Web service operation 'WUResubmit' (returns error code or SOAP_OK)
	virtual	int WUResubmit(_ns6__WUResubmit *ns6__WUResubmit, _ns6__WUResubmitResponse *ns6__WUResubmitResponse);

	/// Web service operation 'WUResult' (returns error code or SOAP_OK)
	virtual	int WUResult(_ns6__WUResult *ns6__WUResult, _ns6__WUResultResponse *ns6__WUResultResponse);

	/// Web service operation 'WUResultBin' (returns error code or SOAP_OK)
	virtual	int WUResultBin(_ns6__WUResultBin *ns6__WUResultBin, _ns6__WUResultBinResponse *ns6__WUResultBinResponse);

	/// Web service operation 'WUResultSummary' (returns error code or SOAP_OK)
	virtual	int WUResultSummary(_ns6__WUResultSummary *ns6__WUResultSummary, _ns6__WUResultSummaryResponse *ns6__WUResultSummaryResponse);

	/// Web service operation 'WUResultView' (returns error code or SOAP_OK)
	virtual	int WUResultView(_ns6__WUResultView *ns6__WUResultView, _ns6__WUResultViewResponse *ns6__WUResultViewResponse);

	/// Web service operation 'WURun' (returns error code or SOAP_OK)
	virtual	int WURun(_ns6__WURun *ns6__WURun, _ns6__WURunResponse *ns6__WURunResponse);

	/// Web service operation 'WUSchedule' (returns error code or SOAP_OK)
	virtual	int WUSchedule(_ns6__WUSchedule *ns6__WUSchedule, _ns6__WUScheduleResponse *ns6__WUScheduleResponse);

	/// Web service operation 'WUShowScheduled' (returns error code or SOAP_OK)
	virtual	int WUShowScheduled(_ns6__WUShowScheduled *ns6__WUShowScheduled, _ns6__WUShowScheduledResponse *ns6__WUShowScheduledResponse);

	/// Web service operation 'WUSubmit' (returns error code or SOAP_OK)
	virtual	int WUSubmit(_ns6__WUSubmit *ns6__WUSubmit, _ns6__WUSubmitResponse *ns6__WUSubmitResponse);

	/// Web service operation 'WUSyntaxCheckECL' (returns error code or SOAP_OK)
	virtual	int WUSyntaxCheckECL(_ns6__WUSyntaxCheckECL *ns6__WUSyntaxCheckECL, _ns6__WUSyntaxCheckResponse *ns6__WUSyntaxCheckResponse);

	/// Web service operation 'WUUpdate' (returns error code or SOAP_OK)
	virtual	int WUUpdate(_ns6__WUUpdate *ns6__WUUpdate, _ns6__WUUpdateResponse *ns6__WUUpdateResponse);

	/// Web service operation 'WUUpdateQueryEntry' (returns error code or SOAP_OK)
	virtual	int WUUpdateQueryEntry(_ns6__WUUpdateQueryEntry *ns6__WUUpdateQueryEntry, _ns6__WUUpdateQueryEntryResponse *ns6__WUUpdateQueryEntryResponse);

	/// Web service operation 'WUWaitCompiled' (returns error code or SOAP_OK)
	virtual	int WUWaitCompiled(_ns6__WUWaitCompiled *ns6__WUWaitCompiled, _ns6__WUWaitResponse *ns6__WUWaitResponse);

	/// Web service operation 'WUWaitComplete' (returns error code or SOAP_OK)
	virtual	int WUWaitComplete(_ns6__WUWaitComplete *ns6__WUWaitComplete, _ns6__WUWaitResponse *ns6__WUWaitResponse);
};
#endif
