#include "soapH.h"
#include "soapws_USCOREaccountServiceSoapProxy.h"
#include "soapWsAttributesServiceSoapProxy.h"
#include "soapWsDfuServiceSoapProxy.h"
#include "soapWsSMCServiceSoapProxy.h"
#include "soapWsTopologyServiceSoapProxy.h"
#include "soapWsWorkunitsServiceSoapProxy.h"
#include "gsoapWinInet.h"
