//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by en_us.rc
//
#define IDC_BUTTON_REPLACE              12
#define IDC_BUTTON_CHECKSYNTAX          13
#define IDC_BUTTON_REPLACE_ALL          14
#define IDC_EDIT_CURR                   15
#define IDC_STATIC_PROMPT               16
#define IDC_CREATE_ATTR                 17
#define IDC_EDIT_USER                   18
#define IDC_EDIT_USER_RHS               19
#define IDC_EDIT_PASSWORD               20
#define IDC_EDIT_CONFIRM                21
#define IDC_EDIT_PASSWORD_RHS           22
#define IDS_GQB_ATTRROLLBACK            23
#define IDS_GQB_INVALIDFIELDNAME        24
#define IDS_GQB_OPENPROJECT             25
#define IDS_GQB_SWITCH_SPRAY_TYPE       26
#define IDC_LOCAL_PATH                  27
#define IDC_LOCAL_PATH_RHS              28
#define IDC_STATIC_CONFIGURATION        29
#define IDC_STATIC_USER                 30
#define IDC_STATIC_PASSWORD             31
#define IDC_COMBO_CONFIG                32
#define IDC_STATIC_USER2                33
#define IDC_STATIC_CONFIRM              34
#define IDC_STATIC_CONFIGURATION_RHS    35
#define IDC_COMBO_CONFIG_RHS            36
#define IDC_STATIC_USER_RHS             37
#define IDC_STATIC_PASSWORD_RHS         38
#define IDD_LOGIN                       39
#define IDD_GOTO                        40
#define IDD_ABOUTBOX                    41
#define IDP_OLE_INIT_FAILED             42
#define IDD_PREF                        43
#define IDB_WRITESMALL                  44
#define IDB_WRITELARGE                  45
#define IDB_MAIN                        46
#define IDB_BUTTONS                     47
#define IDB_FILELARGE                   48
#define IDB_FILESMALL                   49
#define IDR_POPUP_EDIT                  50
#define IDB_REP                         51
#define IDD_GRAPHVIEW                   52
#define IDR_BUILDERWINDOW               53
#define IDD_BUILDERVIEW                 54
#define IDD_ATTRIBUTEVIEW               55
#define IDR_GRAPHWINDOW                 56
#define IDR_ATTRIBUTEWINDOW             57
#define IDR_MAINFRAME_GQB               58
#define IDS_PROCESS_HEADER              59
#define IDS_PROP_HEADER                 60
#define IDS_PREVIEW_HEADER              61
#define IDS_DELETE_RECORDS_GQB          62
#define IDS_GQB_TRANSFROMSAVE           63
#define IDS_GQB_NORECORD                64
#define IDS_INPUT_ATTR_PROMPT           65
#define IDS_OUTPUT_ATTR_PROMPT          66
#define IDS_TRANSFORM_ATTR_PROMPT       67
#define IDS_GQB_RECORDTYPESAVE          68
#define IDS_TRANSFORM_ATTR_CREATE_PROMPT 69
#define IDS_TRANSFORM_ATTR_REUSE_PROMPT 70
#define IDS_GQB_NOTRANSFORM_DOCREATE    71
#define IDS_LAYOUT_ATTR_REUSE_PROMPT    72
#define IDS_GQB_NORECORD_DOCREATE       73
#define IDS_LAYOUT_ATTR_CREATE_PROMPT   74
#define IDS_GQB_NOCREATEATTR            75
#define IDR_WINDOWS_MENU                76
#define IDS_SPRAY_ATTR_PROMPT           77
#define IDS_BAD_ATTRNAME                78
#define IDS_GQB_NO_SPRAYCALL            79
#define IDS_GQB_ATTRSAVE                80
#define IDS_GQB_ATTRSAVEAS              81
#define IDS_GQB_ATTRSAVEAS_OVERWRITE    82
#define IDS_CANT_CHECKOUT_ATTR          83
#define IDS_AUTOCHECKIN_COMMENTS        84
#define IDS_SPLITCOLUMNS_PROMPT         85
#define IDS_GQB_NO_DESPRAYCALL          86
#define IDS_WINDOWS_MANAGER             87
#define IDI_PROPERTIES_WND              88
#define IDI_PROPERTIES_WND_HC           89
#define IDB_SORT_24                     90
#define IDR_POPUP_SORT                  91
#define IDR_POPUP_EXPLORER              92
#define IDB_CLASS_VIEW_24               93
#define IDR_MENU_IMAGES                 94
#define IDD_WIZ97_WELCOME               95
#define IDB_WIZ97_HEADER                96
#define IDD_WIZ97_COMPLETION            97
#define IDB_WIZ97_WATERMARK             98
#define IDD_WIZ97_PATHFILTER            99
#define IDR_PROPERTIES                  100
#define IDD_WIZ97_ANALYZE               101
#define IDD_WIZ97_SAMPLE                102
#define IDR_BREAKPOINTS                 103
#define IDD_WIZ97_TARGET                104
#define IDR_THEME_MENU                  105
#define IDI_FOLDER_OPEN                 106
#define IDI_FOLDER_CLOSED               107
#define IDI_PINNED                      108
#define IDI_UNPINNED                    109
#define IDI_ICON_UPFOLDER               110
#define IDI_ICON_REFRESH                111
#define IDD_FIND                        112
#define IDD_REPLACE                     113
#define IDR_MDICHILD                    114
#define IDB_INFO                        115
#define IDD_MULTIRESULTVIEW             116
#define IDD_REPOSITORY                  117
#define IDI_LOCKED                      118
#define IDI_SANDBOXED                   119
#define IDI_CHECKEDOUT_SANDBOXED        120
#define IDR_POPUP_WORKUNIT              121
#define IDI_CHECKEDOUT                  122
#define IDR_POPUP_REPOSITORY            123
#define IDI_ORPHANED                    124
#define IDR_POPUP_OPEN                  125
#define IDD_RESULTVIEW                  126
#define IDR_POPUP_RESULTS               127
#define IDR_MAINFRAME                   128
#define IDB_REP_MASK                    129
#define IDD_OUTPUT                      130
#define IDD_COMMENT_HISTORY             131
#define IDD_INSERT_ATTRIBUTE            132
#define IDS_RIBBON_FILE                 133
#define IDD_EXCEPTIONVIEW               134
#define IDD_SELECT_MODULE               135
#define IDS_RIBBON_NEW                  136
#define IDD_DIALOG_DIFF                 137
#define IDS_RIBBON_OPEN                 138
#define IDD_COMMENT_NOHISTORY           139
#define IDR_TAB_CONTEXT                 140
#define IDS_RIBBON_SAVE                 141
#define IDD_OPEN_WORKUNIT               142
#define IDR_POPUP_RESULTS_SUMMARY       143
#define IDS_RIBBON_SAVEAS               144
#define IDD_REPOSITORYFILTER            145
#define IDR_POPUP_RESULTS_EXCEPTION     146
#define IDS_RIBBON_PRINT                147
#define IDD_WORKUNITTREE                148
#define IDR_POPUP_HISTORY               149
#define IDS_RIBBON_PRINT_LABEL          150
#define IDD_SUMMARYVIEW                 151
#define IDR_POPUP_AMT_VIEW              152
#define IDS_RIBBON_PRINT_QUICK          153
#define IDD_ATTRLOOKUP                  154
#define IDS_RIBBON_PRINT_PREVIEW        155
#define IDS_RIBBON_PRINT_SETUP          156
#define IDS_RIBBON_CLOSE                157
#define IDD_CHANGEPASSWORD              158
#define IDS_RIBBON_RECENT_DOCS          159
#define IDD_SYNTAX                      160
#define IDS_RIBBON_EXIT                 161
#define IDD_WORKUNITACTIVE              162
#define IDS_RIBBON_HOME                 163
#define IDD_SIMPLE_PROMPT               164
#define IDS_RIBBON_CLIPBOARD            165
#define IDS_RIBBON_PASTE                166
#define IDS_RIBBON_CUT                  167
#define IDS_RIBBON_COPY                 168
#define IDS_RIBBON_SELECTALL            169
#define IDD_WORKUNITFILTER              170
#define IDS_RIBBON_WINDOW               172
#define IDS_RIBBON_WINDOWS              173
#define IDD_DIALOG_NESTED_DATASET       174
#define IDS_RIBBON_STYLE                175
#define IDD_ATTRDEPEND                  176
#define IDS_RIBBON_STYLE_TIP            177
#define IDR_POPUP_MDITABS               178
#define IDS_RIBBON_STATUSBAR            179
#define IDS_RIBBON_VIEW                 180
#define IDD_ATTRVERIFY                  181
#define IDC_MARGIN                      182
#define IDD_LOGIN_AMT                   183
#define IDR_MAINFRAME_AMT               184
#define IDR_POPUP_GRAPH_GRAPH           185
#define IDR_POPUP_GRAPH_SUBGRAPH        186
#define IDD_LANDINGZONE                 187
#define IDR_POPUP_GRAPH_VERTEX          188
#define IDD_DFUFILTER                   189
#define IDR_POPUP_DFU                   190
#define IDD_DFU                         191
#define IDR_POPUP_NEW                   192
#define IDD_WIZ97_TARGETQB              193
#define IDR_POPUP_GRAPH_EDGE            194
#define IDD_PREF_SERVER                 195
#define IDR_RD_POPUP_GRAPH_VERTEX       196
#define IDD_PREF_EDITOR                 197
#define IDR_RD_POPUP_GRAPH_SUBGRAPH     198
#define IDD_PREF_RESULTS                199
#define IDR_RD_POPUP_GRAPH_GRAPH        200
#define IDS_EXPLORER                    201
#define IDD_PREF_OTHER                  202
#define IDR_RD_POPUP_GRAPH_EDGE         203
#define IDS_EDIT_MENU                   204
#define IDD_PREF_COLOR                  205
#define IDD_AMT_COMPARE                 206
#define IDD_ATTRVERIFY2                 207
#define IDI_UNCHECKED                   208
#define IDI_PARTIALCHECK                209
#define IDD_ROXIE_ADDBREAKPOINT         210
#define IDI_CHECKED                     211
#define IDD_DIALOG_SEARCH               212
#define IDI_RADIO_CHECKED               213
#define IDI_RADIO_UNCHECKED             214
#define IDI_BLANK                       215
#define IDI_BUSY                        216
#define IDB_TRUETYPE_FONTTYPE           217
#define IDR_POPUP_ADVANCED              218
#define IDB_COLORSMALL                  219
#define IDD_DEBUGVIEW                   220
#define IDB_COLORLARGE                  221
#define IDD_LABEL                       221
#define IDB_DEBUGGER                    222
#define IDD_ATTRSYNTAX                  222
#define IDB_MENU_IMAGES_24              223
#define IDD_PREF_COMPILER               223
#define IDB_AMT_WRITELARGE              224
#define IDB_AMT_WRITESMALL              225
#define IDB_AMT_FILESMALL               226
#define IDB_AMT_FILELARGE               227
#define IDC_EDIT_USERFILTER             228
#define IDB_MAIN_AMT                    228
#define IDC_EDIT_OUTPUT                 229
#define IDC_EDIT_COMMENT                230
#define IDC_EDIT_LABEL                  231
#define IDC_EDIT_EXCEPTION              232
#define IDC_EDIT_SEARCH                 233
#define IDC_EDIT_MAXRUNTIME             234
#define IDC_EDIT_MAXCOUNT               235
#define IDC_EDIT_ECL                    236
#define IDC_COMBO_CLUSTER               237
#define IDC_BUTTON_UPDATE               239
#define IDC_COMBO_STATE                 240
#define IDC_BUTTON_GO                   241
#define IDC_COMBO_FIND                  242
#define IDC_CHECK_WHOLE_WORD            243
#define IDC_EDIT_TOPOLOGYSERVER         244
#define IDC_COMBO_LABEL                 245
#define IDC_CHECK_CASE                  246
#define IDC_BUTTON_DEBUG                247
#define IDC_CHECK_WILDCARD              247
#define IDC_RADIO_UP                    248
#define IDC_RADIO_DOWN                  249
#define IDC_EDIT_MODULE                 250
#define IDC_CHECK_REGEX                 250
#define IDC_CHECK_SEARCHTOOLTIP         251
#define IDC_COMBO_REPLACE               252
#define IDC_EDIT_TABWIDTH               253
#define IDC_TREE_REPOSITORY             254
#define IDC_STATIC_ACTION               255
#define IDC_COMBOBOXEX_ACTION           256
#define IDC_STATIC_CONDITIONTYPE        257
#define IDC_SLIDER_ZOOM                 258
#define IDC_COMBOBOXEX_CONDITION        259
#define IDC_EDIT_WORKUNITSERVER         260
#define IDC_STATIC_EXPRESSION           261
#define IDC_EDIT_ATTRIBUTESERVER        262
#define IDC_EDIT_CONDITION              263
#define IDC_EDIT_VALUE                  265
#define IDC_STATIC_CONDITIONTYPE2       266
#define IDC_EDIT_ACCOUNTSERVER          267
#define IDC_STATIC_PRODUCT              268
#define IDC_COMBOBOXEX_COUNT            269
#define IDC_EDIT_SMCSERVER              270
#define IDC_STATIC_COUNT                271
#define IDC_SAVE_AS                     272
#define IDC_LOGIN_PREFS                 273
#define IDC_BUTTON_SEARCH               274
#define IDC_STATIC_EXPRESSION2          275
#define IDC_ANALYZE_FILE                276
#define IDC_CONFIG_DELETE               277
#define IDC_LOGIN_PREFS_RHS             278
#define IDC_BUTTON_CLEAR                279
#define IDC_STATIC_HITCOUNT             280
#define IDC_BUTTON_LAYOUT_ATTR_PREVIEW  281
#define IDC_STATIC_FIND                 282
#define IDC_CHECK_MAINTAININDENT        283
#define IDC_SPIN_COUNT                  284
#define IDC_EDIT_COPYASECL              285
#define IDC_STATIC_FIND2                286
#define IDC_EDIT_COUNT                  288
#define IDC_BUTTON_LAYOUT_ANALYZE       289
#define IDC_STATIC_AUTOSAVEFREQ         290
#define IDC_BUTTON_LAYOUT_FILE_CONFIGURE 291
#define IDC_STATIC_FONTSIZE             292
#define IDC_CHECK_CASESENSITIVE         293
#define IDC_CHECK_OPENMDICHILDMAX       294
#define IDC_STATIC_FIELD                295
#define IDC_CHECK_OPENMDICHILDMAX2      295
#define IDC_CHECK_SYNCREPOSITORY        295
#define IDC_SPIN_AUTOSAVEFREQ           296
#define IDC_COMBO_CONDITION             297
#define IDC_CHECK_AUTOCOMPLETEONDOT     297
#define IDC_EDIT_AUTOSAVEFREQ           298
#define IDC_STATIC_VALUE                299
#define IDC_CHECK_DOUBLECLICKSEL        299
#define IDC_EDIT_WORKUNITPOLL           302
#define IDC_CHECK_TABUSESPACES          302
#define IDC_LIST_RESULTS                303
#define IDC_EDIT_WORKUNITFETCHLIMIT     303
#define IDC_SPIN_WORKUNITPOLL           304
#define IDC_IE_PLACEHOLDER              305
#define IDC_SPIN_WORKUNITFETCHLIMIT     305
#define IDC_STATIC_PLACEHOLDER          306
#define IDC_EDIT_LIMITRESULT            307
#define IDC_ECL_PLACEHOLDER             308
#define IDC_STATIC_TOPOLOGY             309
#define IDC_SPIN_LIMITRESULT            310
#define IDC_EDIT_RESULT_FONTSIZE        312
#define IDC_SPIN_RESULT_FONTSIZE        313
#define IDC_EDIT_SPRAYSERVER            314
#define IDC_LOCATE                      315
#define IDC_CHECK_ADVANCED              316
#define IDC_CHECK_SEARCHTOOLTIPS        317
#define IDC_CHECK_BOLD                  318
#define IDC_CHECK_SANDBOX               319
#define IDC_CHECK_ALLUSERS              320
#define IDC_CHECK_SANDBOX2              320
#define IDC_CHECK_WORKSPACES            320
#define IDC_CHECK_USER                  321
#define IDC_CHECK_MODIFIEDSINCE         322
#define IDC_CHECK_SCHEDULE              323
#define IDC_XB_ATTR_LAYOUT              324
#define IDC_EDIT_DFUSERVER              325
#define IDC_LIST_HISTORY                326
#define IDC_CHECK_CLUSTER               327
#define IDC_CHECK_SANDBOXED             328
#define IDC_BUTTON_ARCHIVE              329
#define IDC_XB_ATTR_FILE                330
#define IDC_CHECK_DISABLEINVOKE         331
#define IDC_CHECK_STATE                 332
#define IDC_CHECK_DISABLEINVOKE2        332
#define IDC_CHECK_DISABLEAUTOUPDATE     332
#define IDC_CHECK_LOCKED                333
#define IDC_CHECK_SYNTAXPLUS            334
#define IDC_XB_ATTR_SPRAY               335
#define IDC_CHECK_IGNOREWHITESPACE      336
#define IDC_CHECK_DATETIMERANGE         337
#define IDC_CHECK_IGNOREWHITESPACE2     337
#define IDC_CHECK_IGNORESERVERVERSION   337
#define IDC_CHECK_CHECKEDOUT            338
#define IDC_XB_ATTR_DESPRAY             339
#define IDC_CHECK_ORPHANED              340
#define IDC_COMBO_MODULE                341
#define IDC_CHECK_LINENO                342
#define IDC_CHECK_TREE                  343
#define IDC_STATIC_FONT                 344
#define IDC_STATIC_FONT2                345
#define IDC_STATIC_HISTORY              346
#define IDC_STATIC_FONT3                347
#define IDC_STATIC_COMMENT              348
#define IDC_STATIC_CLUSTER              349
#define IDC_DATE                        350
#define IDC_COMBO_MODE                  351
#define IDC_TIME                        352
#define IDC_DATETIMEPICKER_DATE         353
#define IDC_STATIC_LABEL                354
#define IDC_DATETIMEPICKER_TIME         355
#define IDC_STATIC_QUEUECLUSTER         356
#define IDC_TREE_WORKUNIT               357
#define IDC_DATETIMEPICKER_DATETO       358
#define IDC_DATETIMEPICKER_TIMETO       359
#define IDC_COMBO_CLUSTERS              360
#define IDC_STATIC_OLD                  361
#define IDC_EDIT_OLD                    362
#define IDC_STATIC_NEW                  363
#define IDC_EDIT_NEW                    364
#define IDC_CHECK_SSL                   365
#define IDC_LIST_SYNTAX                 366
#define IDC_EDIT                        367
#define IDC_SPIN_MAXRUNTIME             368
#define IDC_DATETIMEPICKER_DATEFROM     369
#define IDC_DATETIMEPICKER_TIMEFROM     370
#define IDC_SPIN_MAXCOUNT               371
#define IDC_EDIT_LAYOUT_INPUTFILE       372
#define IDC_EDIT_IPADDRESS              373
#define IDC_BUTTON_FILE_NEW_PICK        374
#define IDC_STATIC_MSG                  375
#define IDC_STATIC_WARNING              376
#define IDC_STATIC_MSG2                 376
#define IDC_STATIC_UPGRADE              376
#define IDC_STATIC_MSG_RHS              377
#define IDC_STATIC_BEVEL                378
#define IDC_STATIC_VERSION              379
#define IDC_STATIC_SERVER               380
#define IDC_STATIC_ECLWATCH             381
#define IDC_COMBO_TYPE                  382
#define IDC_COMBO_CHAR_TYPE             383
#define IDC_COMBO_DROPZONE_IMPORT       384
#define IDC_EDIT_ATTR_LAYOUT            385
#define IDC_EDIT_ATTR_FILE              386
#define IDC_EDIT_ATTR_SPRAY             387
#define IDC_EDIT_SOURCE_PATH            388
#define IDC_EDIT_NEW_FILE               389
#define IDC_EDIT_DFU                    390
#define IDC_EDIT_RECORD_SIZE            391
#define IDC_EDIT_MAX_RECORD_SIZE_XML_SPRAY 392
#define IDC_EDIT_ROW_TAG                393
#define IDC_RADIO_FIXED_WIDTH           394
#define IDC_RADIO_DELIMITED             395
#define IDC_EDIT_START_ROW              396
#define IDC_COMBO_RECORD_WIDTH          397
#define IDC_COMBO_FIELD_DELIMITER       398
#define IDC_EDIT_VARRECORD_SIZE         399
#define IDC_GROUP_FILE_DATA_FORMAT1     400
#define IDC_STATIC_START_IMPORT         401
#define IDFINISH_IMPORT                 402
#define IDBACK_TOIMPORT1                403
#define IDC_EDIT_RESULT_ANALYSIS        404
#define IDC_EDIT_LOGICAL_NAME           405
#define IDC_BUTTON_SPRAY_ATTR_PICK      406
#define IDC_EDIT_SPRAY_ATTR             407
#define IDC_BUTTON_HIDE_EDITOR          408
#define IDC_STATIC_LIMITRESULT          409
#define IDC_BUTTON_ADVANCED             410
#define IDC_STATIC_DEBUG                411
#define IDC_STATIC_MAXRUNTIME           412
#define IDC_EDIT_XML_FILE_PATH          413
#define IDC_EDIT_DEBUG                  414
#define IDC_BUTTON_DESPRAY_ATTR_PICK    415
#define IDC_EDIT_ATTR_DESPRAY           417
#define IDC_BUTTON_PICKDZ               418
#define IDC_EDIT_DZ_PATH                419
#define IDC_EDIT_DZ_IP                  420
#define IDC_STATIC_CAPTION              421
#define IDC_BUTTON_DZ_REFRESH           422
#define IDC_STATIC_TO                   422
#define IDC_XB_ADVANCED_NAMING          423
#define IDC_BUTTON_FILE_NEW_MODULE_PICK 424
#define IDC_EDIT_NEW_LOGICAL_FILE_NAME  425
#define IDC_STATIC_ICON                 426
#define IDC_COMBO_SPRAY_GROUP           427
#define IDC_STATIC_MODULE               428
#define IDC_LOCAL_PATH_BROWSE           429
#define IDC_CHECK_TOOLTIP               430
#define IDC_LOCAL_PATH_BROWSE_RHS       431
#define IDC_COMBO_LANDINGZONE           432
#define IDC_STATIC_LANDINGZONE          433
#define IDC_TREE_LANDINGZONE            434
#define IDC_TREE_COMPARE                435
#define IDC_TREE_DFU                    436
#define IDC_EDIT_PREFIX                 437
#define IDC_EDIT_CLUSTER                438
#define IDC_STATIC_LOGICAL              439
#define IDC_BUTTON_COPY                 440
#define IDC_EDIT_DESCRIPTION            441
#define IDC_SHEET                       442
#define IDC_EDIT_LOGICAL                443
#define IDC_EDIT_OWNER                  444
#define IDC_STATIC_SIZE                 445
#define IDC_COMBO_FONT                  446
#define IDC_COMBO_FONTSIZE              447
#define IDC_BUTTON_FOREGROUND           448
#define IDC_BUTTON_BACKGROUND           449
#define IDC_COMBO_ELEMENT               450
#define IDC_STATIC_ELEMENT              451
#define IDC_BUTTON_GPF                  452
#define IDC_BUTTON_DEFAULTS             453
#define IDC_BUTTON_INSTALLVERSION       453
#define IDC_COMBO_SOURCEMODE            454
#define IDC_BUTTON_INSTALLVERSION2      454
#define IDC_BUTTON_UNINSTALLVERSION     454
#define IDC_COMBO_LHS                   455
#define IDC_COMBO_TARGETMODE            456
#define IDC_COMBO_RHS                   457
#define IDC_STATIC_LHS                  458
#define IDC_LIST_ATTRIBUTES             459
#define IDC_STATIC_RHS                  460
#define IDC_STATIC_SOURCEMODE           461
#define IDC_STATIC_SOURCE               462
#define IDC_STATIC_TARGETMODE           463
#define IDC_STATIC_PATH                 464
#define IDC_CHECK_SHOWCRLF              465
#define IDC_STATIC_PATH_RHS             466
#define IDC_EDIT_FIELD                  467
#define IDC_LIST_FILEBROWSER            468
#define IDC_EDIT_FILEPATH               469
#define IDC_BUTTON_UP                   470
#define IDC_EDIT_IP                     471
#define IDC_WIZ97_EXTERIOR_TITLE        472
#define IDC_WIZ97_EXTERIOR_DESC         473
#define IDC_WIZ97_WELCOME_NOTAGAIN      474
#define IDC_RICHEDIT2_STATUS            475
#define IDC_WIZ97_SUMMARY               476
#define IDC_WIZ97_EXTERIOR_CLICKFINISH  477
#define IDC_EDIT_DESTINATION            478
#define IDC_STATIC_PREFIX               479
#define IDC_EDIT_TARGET                 480
#define IDC_WIZ97_BULLET1               481
#define IDC_WIZ97_BULLET2               482
#define IDC_WIZ97_BULLET3               483
#define IDC_STATIC_TARGET               484
#define IDC_WIZ97_BULLET4               485
#define IDC_BUTTON_TARGET               486
#define IDC_WIZ97_BULLET1_DESC          487
#define IDC_WIZ97_BULLET2_DESC          488
#define IDC_WIZ97_BULLET3_DESC          489
#define IDC_WIZ97_BULLET4_DESC          490
#define IDS_RIBBON_STYLE_DESC           491
#define IDR_POPUP_DROP_MDITABS          492
#define ID_VIEW_TABLOOK_STYLE_3D        493
#define ID_VIEW_TABLOOK_STYLE_FLAT      494
#define ID_VIEW_TABLOOK_STYLE_FLAT_SHARED_HORZ_SCROLL 495
#define ID_VIEW_TABLOOK_STYLE_3D_SCROLLED 496
#define ID_VIEW_TABLOOK_STYLE_3D_ONENOTE 497
#define ID_VIEW_TABLOOK_STYLE_3D_VS2005 498
#define ID_VIEW_TABLOOK_STYLE_3D_ROUNDED 499
#define ID_VIEW_TABLOOK_STYLE_3D_ROUNDED_SCROLL 500
#define ID_VIEW_TABLOOK_STYLE_CLOSE_ON_TAB 501
#define IDC_ECLWATCH_GRAPHCONTROL       502
#define IDC_EDIT_LHS                    503
#define IDC_EDIT_RHS                    504
#define IDC_BUTTON_CLEARSEARCH          505
#define IDC_COMBO_QUEUECLUSTER          506
#define IDC_CHECK_ERRORS                507
#define IDC_CHECK_WARNINGS              508
#define IDC_BUTTON_ECLFOLDERADD         509
#define IDC_CHECK_INFORMATION           510
#define IDC_STATIC_FETCHLIMIT           510
#define IDC_BUTTON_MOVEUP               510
#define ID_OPENALLWITHERRORS            511
#define IDC_BUTTON_ECLFOLDERADD2        511
#define IDC_BUTTON_ECLWORKINGFOLDER     513
#define IDC_EDIT_LOCATION               514
#define IDC_EDIT_ARGUMENTS              515
#define IDC_STATIC_ARGUMENTS            516
#define IDC_EDIT_ECLWORKINGFOLDER       517
#define IDC_STATIC_ECLWORKINGFOLDER     518
#define IDC_BUTTON_ECLCOMPILER          519
#define IDC_LIST_ECLFOLDERS             520
#define IDC_STATIC_ECLFOLDERS           521
#define IDC_BUTTON_ECLFOLDERDELETE      522
#define IDC_STATIC_ONLYVIALOGIN         523
#define IDC_BUTTON_MOVEDOWN             523
#define IDC_STATIC_WUARGUMENTS          524
#define IDC_COMBO1                      524
#define IDC_COMBO_MODULES               524
#define IDC_EDIT_ARGUMENTS2             525
#define IDC_EDIT_WUARGUMENTS            525
#define IDC_STATIC_COMPILER             525
#define IDC_STATIC_LOCATION             526
#define IDC_CHECK_OVERRIDEDEFAULTCOMPILERSELECTION 527
#define ID_COL_PANE                     32772
#define ID_WINDOW_MANAGER               32773
#define ID_ROW_PANE                     32774
#define ID_PROPERTIES                   32775
#define ID_OPEN                         32776
#define ID_OPEN_WITH                    32777
#define ID_DUMMY_COMPILE                32778
#define ID_SORTING_GROUPBYTYPE          32779
#define ID_SORTING_SORTALPHABETIC       32780
#define ID_SORTING_SORTBYTYPE           32781
#define ID_SORTING_SORTBYACCESS         32782
#define ID_SORTPROPERTIES               32783
#define ID_PROPERTIES1                  32784
#define ID_PROPERTIES2                  32785
#define ID_EXPAND_ALL                   32786
#define ID_TOOLS_MACRO                  32787
#define ID_VIEW_APPLOOK_WIN_2000        32788
#define ID_VIEW_APPLOOK_OFF_XP          32789
#define ID_VIEW_APPLOOK_WIN_XP          32790
#define ID_VIEW_APPLOOK_OFF_2003        32791
#define ID_VIEW_APPLOOK_VS_2005         32792
#define ID_VIEW_APPLOOK_VS_2008         32793
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   32794
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  32795
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 32796
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   32797
#define ID_VIEW_APPLOOK_WIN7_SCENIC     32798
#define ID_EDIT_FINDREPLACECMD          32799
#define ID_ECL_CHECKSOMPLEXITY          32800
#define ID_ECL_CHECKCOMPLEXITY          32801
#define ID_ECL_CHECKDEPENDENCY          32802
#define ID_BROWSER_NEW                  32803
#define ID_BROWSER_STOP                 32804
#define ID_BROWSER_REFRESH              32805
#define ID_BROWSER_BACK                 32806
#define ID_BROWSER_FORWARD              32807
#define ID_GRAPH_LAYOUT                 32808
#define ID_FORMAT_FONTCOLOR             32809
#define ID_FORMAT_FILLCOLOR             32810
#define ID_GRAPH_ZOOMTOFIT              32811
#define ID_GRAPH_ZOOMTOWIDTH            32812
#define ID_DEBUGGER_DETACH              32813
#define ID_EDIT_FINDNEXT                32814
#define ID_DEBUGGER_ABORT               32815
#define ID_EDIT_FINDPREV                32816
#define ID_DEBUGGER_CONTINUE            32817
#define ID_EDIT_GOTO                    32818
#define ID_DEBUGGER_STEPGRAPH           32819
#define ID_DEBUGGER_STEP                32820
#define ID_DEBUGGER_NEXT                32821
#define ID_DEBUGGER_REMOVEALLBREAKPOINTS 32822
#define ID_DEBUGGER_ZOOM                32825
#define ID_DEBUGGER_RECENTER            32826
#define ID_DEBUGGER_LAYOUT              32827
#define ID_DEBUGGER_SOCKETPROGRESS      32828
#define ID_DEBUGGER_LAYOUTPROGRESS      32829
#define ID_REPOSITORY_INVOKE            32830
#define ID_WORKUNIT_UNFOLLOWUP          32831
#define ID_COPY_WUID                    32832
#define ID_RESULT_DRILLDOWNSELECT       32833
#define ID_RESULT_DRILLDOWN_SELECT      32834
#define ID_RESULT_DRILLDOWNSINGLESELECT 32835
#define ID_RESULT_DRILLDOWNSINGLE_SELECT 32836
#define ID_RESULT_DRILLDOWN2SELECT      32837
#define ID_RESULT_DRILLDOWN2_SELECT     32838
#define ID_ECL_GO                       32839
#define ID_EDIT_ADDTOREP                32840
#define ID_STATUSBAR_PANE1              32841
#define ID_STATUSBAR_PANE2              32842
#define ID_STATUSBAR_PANE3              32843
#define ID_ECL_CHECKSYNTAX              32844
#define ID_ECL_NEXTERROR                32845
#define ID_ECL_PREVIOUSERROR            32846
#define ID_WORKUNIT_DELETE              32847
#define ID_WORKUNIT_ABORT               32848
#define ID_WORKUNIT_RESUBMIT            32849
#define ID_WORKUNIT_REFRESH             32850
#define ID_WORKUNIT_BROWSEECLWATCH      32851
#define ID_WORKUNIT_OPENECL             32852
#define ID_FILE_SAVE_ALL                32853
#define ID_WINDOW_CLOSE                 32854
#define ID_REPOSITORY_OPEN              32855
#define ID_REPOSITORY_OPENBUILDER       32856
#define ID_REPOSITORY_COPY              32857
#define ID_WORKUNIT_OPENRESULTS         32858
#define ID_REPOSITORY_CHECKOUT          32859
#define ID_REPOSITORY_CHECKIN           32860
#define ID_REPOSITORY_ROLLBACK          32861
#define ID_EDIT_MATCHBRACE              32862
#define ID_EDIT_SELECTTOBRACE           32863
#if _WTL_VER < 0x0900
#define ID_EDIT_DELETE                  32864
#endif
#define ID_EDIT_COMPLETEWORD            32865
#define ID_EDIT_BLOCKCOMMENT            32866
#define ID_EDIT_BOXCOMMENT              32867
#define ID_EDIT_LOWERCASE               32868
#define ID_EDIT_UPPERCASE               32869
#define ID_ATTRIBUTE_RENAME             32870
#define ID_FILE_PREFERENCES             32871
#define ID_ECL_CLEARERRORS              32872
#define ID_ECL_SYNCTOC                  32873
#define ID_ECL_GOTO                     32874
#define ID_ECL_GOTOSYNCTOC              32875
#define ID_FILE_LOGIN                   32876
#define ID_REPOSITORY_HISTORY           32877
#define ID_EDIT_ADVANCED                32878
#define ID_REPOSITORY_INSERTMODULE      32879
#define ID_FILE_OPENATTRIBUTE           32880
#define ID_FILE_OPENWORKUNIT            32881
#define ID_WORKUNIT_PROTECT             32882
#define ID_WORKUNIT_UNPROTECT           32883
#define ID_EDIT_COPYASCSV               32884
#define ID_FILE_SAVE_ASXML              32885
#define ID_VIEW_REPOSITORY              32886
#define ID_VIEW_REPOSITORYFILTER        32887
#define ID_RESULTS_SHOWCOLUMNINHEX      32888
#define ID_VIEW_PROJECT                 32889
#define ID_EDIT_COPYASECL               32890
#define ID_RESULTS_SELECTROW            32891
#define ID_RESULTS_SELECTCOLUMN         32892
#define ID_TAB_REMOVE_ALL               32893
#define ID_TAB_REMOVE                   32894
#define ID_RESULTS_AUTOSIZECOLUMN       32895
#define ID_REPOSITORY_INVOKE_NONE       32896
#define ID_REPOSITORY_LABEL             32897
#define ID_HISTORY_ROLLBACK             32898
#define ID_RESULTS_AUTOSIZEALLCOLUMNS   32899
#define ID_EDIT_REFORMAT                32900
#define ID_FILE_CHANGEPASSWORD          32901
#define ID_EDIT_ADDTOREP2               32902
#define ID_EDIT_CLEARALL                32903
#define ID_FILE_PAGESETUP               32904
#define ID_REPOSITORY_RENAMEMODULE      32905
#define ID_REPOSITORY_DELETEMODULE      32906
#define ID_REPOSITORY_INSERTATTRIBUTE   32907
#define ID_REPOSITORY_RENAMEATTRIBUTE   32908
#define ID_REPOSITORY_MOVEATTRIBUTE     32909
#define ID_REPOSITORY_DELETEATTRIBUTE   32910
#define ID_SETSTATE_COMPILED            32911
#define ID_SETSTATE_RUNNING             32912
#define ID_SETSTATE_COMPLETED           32913
#define ID_SETSTATE_FAILED              32914
#define ID_SETSTATE_ARCHIVED            32915
#define ID_SETSTATE_ABORTING            32916
#define ID_SETSTATE_ABORTED             32917
#define ID_SETSTATE_BLOCKED             32918
#define ID_SETSTATE_SUBMITTED           32919
#define ID_SETSTATE_SCHEDULED           32920
#define ID_SETSTATE_COMPILING           32921
#define ID_SETSTATE_WAITING             32922
#define ID_RESULT_DELETE_SELECTION      32923
#define ID_REPOSITORY_REFRESH           32924
#define ID_FILE_CHECKIN_ATTR            32925
#define ID_SETPRIORITY_UP               32926
#define ID_SETPRIORITY_DOWN             32927
#define ID_SETPRIORITY_TOP              32928
#define ID_SETPRIORITY_BOTTOM           32929
#define ID_VIEW_SAMPLE                  32930
#define ID_EDIT_ADDTOREP_DEP            32931
#define ID_EDIT_WORDWRAP                32932
#define ID_FILE_LOGOUT                  32933
#define ID_EDIT_REFRESH                 32934
#define ID_RESULT_DRILLDOWNSINGLE_NONE  32935
#define ID_RESULT_DRILLDOWN_NONE        32936
#define ID_WORKUNIT_FOLLOWUP            32937
#define ID_EDIT_SHOW_MATCHING           32938
#define ID_EDIT_SHOW_NOT_MATCHING       32939
#define ID_EDIT_SHOW_ORPHANS            32940
#define ID_EDIT_SHOW_ALL                32941
#define ID_DFU_REFRESH                  32942
#define ID_DFU_COPY                     32943
#define ID_WORKUNIT_SAVEAS              32944
#define ID_FORMAT_FONTBOLD              32945
#define ID_FORMAT_FONTITALIC            32946
#define ID_FORMAT_FONTSTYLE             32947
#define ID_FORMAT_FONTCOLOR_SELECT      32948
#define ID_FORMAT_FILLCOLOR_SELECT      32949
#define ID_RESULT_DRILLDOWN2_NONE       32950
#define ID_FILE_NEWSPRAY                32951
#define ID_HISTORY_LABEL                32952
#define ID_GRAPH_GOTOTARGET             32953
#define ID_GRAPH_GOTOSOURCE             32954
#define ID_EDIT_TOGGLELINENUMBERS       32955
#define ID_GRAPH_MINIMIZE               32956
#define ID_EDIT_COPYASCSV_WITHHEADERS   32957
#define ID_VIEW_WORKUNITS               32958
#define ID_VIEW_ACTIVEWORKUNITS         32959
#define ID_EDIT_EXPANDALL               32960
#define ID_VIEW_WORKUNITFILTER          32961
#define ID_GRAPH_SETBREAKPOINT          32962
#define ID_GRAPH_RESTORESINGLE          32963
#define ID_GRAPH_ADDBREAKPOINT          32964
#define ID_GRAPH_CLEARBREAKPOINT        32965
#define ID_MDI_NEW_VERT_GROUP           32966
#define ID_VIEW_DEBUGDATA               32967
#define ID_MDI_NEW_HORZ_TAB_GROUP       32968
#define ID_VIEW_CRLF                    32969
#define ID_DEBUGGER_BREAK               32970
#define ID_DEBUGGER_REMOVEBREAKPOINT    32971
#define ID_SORTING_DELETE               32972
#define ID_VIEW_DEBUGPROPERTIES         32973
#define ID_MDI_MOVE_TO_PREV_GROUP       32974
#define ID_VIEW_DEBUGBREAKPOINTS        32975
#define ID_DEBUGGER_STEPGRAPHSTART      32976
#define ID_DEBUGGER_STEPGRAPHEND        32977
#define ID_GRAPH_CONTINUEHERE           32978
#define ID_FILE_NEWBUILDER              32979
#define ID_FILE_OPENBUILDER             32980
#define ID_WINDOW_CLOSEALL              32981
#define ID_VIEW_WORKUNITSTREE           32982
#define ID_VIEW_ACTIVEWORKUNITSTREE     32983
#define ID_VIEW_FILTEREDWORKUNITTREEFRAME 32984
#define ID_VIEW_DFU                     32985
#define ID_VIEW_DFUFILTER               32986
#define ID_VIEW_SYNTAX                  32987
#define ID_VIEW_ERROR                   32988
#define ID_VIEW_RESETDOCKEDWINDOWS_DEFAULT_LEFT 32989
#define ID_VIEW_RESETDOCKEDWINDOWS_DEFAULT_RIGHT 32990
#define ID_VIEW_RESETDOCKEDWINDOWS_ALLPINNED_LEFT 32991
#define ID_VIEW_RESETDOCKEDWINDOWS_ALLPINNED_RIGHT 32992
#define ID_VIEW_RESETDOCKEDWINDOWS_ALLUNPINNED_LEFT 32993
#define ID_VIEW_RESETDOCKEDWINDOWS_ALLUNPINNED_RIGHT 32994
#define ID_HELP_LANGUAGEREFERENCE       32995
#define ID_HELP_ERRORREFERENCE          32996
#define ID_HELP_SERVICELIBRARYREFERENCE 32997
#define ID_HELP_CLIENTTOOLS             32998
#define ID_HELP_PROGRAMMERSGUIDE        32999
#define ID_VIEW_CAPTIONBAR              33003
#define ID_VIEW_WHITESPACE              33004
#define ID_MDI_CANCEL                   33005
#define ID_DEBUGGER_SETBREAKPOINT       33006
#define ID_MDI_MOVE_TO_NEXT_GROUP       33007
#define ID_VIEW_DEBUGSEARCH             33008
#define ID_MDI_TABBED_DOCUMENT          33009
#define ID_GRAPH_REFRESH                33010
#define ID_GRAPH_FOLLOWACTIVE           33011
#define ID_MACRO_RECORD                 33014
#define ID_MACRO_PLAY                   33016
#define ID_ADVANCED_SETTABSIZE          33019
#define ID_WORKUNIT_OPENGRAPH           33020
#define ID_WORKUNIT_VIEWEXCEPTIONS      33021
#define ID_BROWSER_IE                   33022
#define ID_APPLY                        33023
#define ID_SORTING_DEGROUP              33024
#define ID_FILE_NEWWORKSPACE            33025
#define ID_PROJECT_SWITCH               33026
#define ID_PROJECT_REMOVE               33027
#define ID_PROJECT_                     33028
#define ID_PROJECT_REFRESH              33029
#define ID_PROJECT_NEW                  33030
#define ID_WORKSPACE_ADD                33031
#define ID_WORKSPACE_REMOVE             33032
#define ID_WORKSPACE_LIST               33033
#define ID_GRAPH_SAVEAS                 33034
#define ID_VIEW_ACTIVE                  33035
#define ID_VIEW_GLOBAL                  33036
#define ID_VIEW_FOUNDONLYACTIVE         33037
#define ID_VIEW_RUNNINGONLYACTIVE       33038
#define ID_VIEW_RUNNINGONLYGLOBAL       33039
#define ID_VIEW_FOUNDONLYGLOBAL         33040
#define ID_DEBUGSOURCEVIEW_LOCATE       33041
#define ID_DEBUGSOURCEVIEW_SETBREAKPOINT 33042
#define ID_DEBUGSOURCEVIEW_ADDBREAKPOINT 33043
#define ID_LOCATE_NONE                  33044
#define ID_REPOSITORY_CHECKINANDREVERT  33045
#define ID_DEBUGGER_SETGLOBALBREAKPOINT 33046
#define ID_VIEW_PROPERTYGRID            33047
#define ID_VIEW_DEBUGPROPERTYGRID       33048
#define ID_REPOSITORY_INSERTMODULEIN    33050
#define ID_ATTRIBUTE_COPYATTRIBUTE      33052
#define ID_REPOSITORY_COPYATTRIBUTE     33053
#define ID_GRAPH_COPYTOOLTIP            33054
#define ID_GRAPH_COPYTOOLTIP33055       33055
#define ID_GRAPH_VERTEX_COPYTOOLTIP     33056
#define ID_GRAPH_EDGE_COPYTOOLTIP       33057
#define ID_GRAPH_MINIMIZEINACTIVE       33058
#define ID_GRAPH2_DOT                   33059
#define ID_GRAPH2_NEATO                 33060
#define ID_GRAPH2_FDP                   33061
#define ID_GRAPH2_TWOPI                 33062
#define ID_GRAPH2_CIRCO                 33063
#define ID_DEPENDEES_FINDSERVICES       33064
#define ID_DEPENDEES_CALCULATEDEPENDENCIES 33065
#define ID_DEPENDEES_SYNCFROMSELECTION  33066
#define ID_DEPENDEES_SYNCTOSELECTION    33067
#define ID_DEPENDEES_CALCULATECROSSREFERENCE 33068
#define ID_DEPENDEES_COPYCROSSREFERENCE 33069
#define ID_GRAPH2_SFDP                  33070
#define ID_GRAPH2_OSAGE                 33071
#define ID_ATTRIBUTE_PASTESELECTION     33072
#define ID_REPOSITORY_PASTE             33073
#define ID_ATTRIBUTE_CHECKSYNTAX        33074
#define ID_REPOSITORY_CHECKSYNTAX       33075
#define ID_DIFFERENCES_PREVIOUS         33076
#define ID_DIFFERENCES_NEXT             33077
#define ID_GO_SUBMIT                    33079
#define ID_GO_COMPILE                   33080
#define ID_GO_DEBUG                     33081
#define ID_EDIT_LOCATEFILEINEXPLORER    33082
#define ID_SYNTAX_COPY                  33083
#define ID_SYNTAX_COPYALL               33084
#define ID_EDIT_COPYALL                 33085
#define ID_SYNTAX_LOCATEERROR           33086
#define ID_EDIT_MODULE_CHECKSUM         33087
#define ID_DEBUGGER_RESTART             33088
#define ATL_IDS_IDLEMESSAGE             0xE001
#define ATL_IDS_SCSIZE                  0xEF00
#define ATL_IDS_SCMOVE                  0xEF01
#define ATL_IDS_SCMINIMIZE              0xEF02
#define ATL_IDS_SCMAXIMIZE              0xEF03
#define ATL_IDS_SCNEXTWINDOW            0xEF04
#define ATL_IDS_SCPREVWINDOW            0xEF05
#define ATL_IDS_SCCLOSE                 0xEF06
#define ATL_IDS_SCRESTORE               0xEF12
#define ATL_IDS_SCTASKLIST              0xEF13
#define ATL_IDS_MDICHILD                0xEF1F
#define ATL_IDS_MRU_FILE                0xEFDA
#define IDR_POPUP_PROJECT               61403
#define IDR_POPUP_DEBUGSOURCEVIEW       61404
#define IDR_POPUP_REPOSITORY_LOCAL      61405
#define IDR_POPUP_WORKUNIT_LOCAL        61406
#define IDR_POPUP_GO                    61407
#define IDR_POPUP_GO2                   61408
#define IDR_POPUP_EEGO                  61409
#define IDR_POPUP_EEGO2                 61410
#define IDR_POPUP_ERRORLOG              61411
#define IDR_POPUP_SYNTAX                61412

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        61413
#define _APS_NEXT_COMMAND_VALUE         33089
#define _APS_NEXT_CONTROL_VALUE         528
#define _APS_NEXT_SYMED_VALUE           61503
#endif
#endif
