#include <atlbase.h>
#include <atlcom.h>
#include <atlwin.h>
#include <atlctl.h>
#include <atlhost.h>
#include <atlsafe.h>
#include <atlstr.h>
#include <atlimage.h>
#include <atlcoll.h>
#include <atlutil.h>
#include <atlfile.h>
