#define _WTL_USE_VSSYM32
#include <atlframe.h>
#include <atlctrls.h>
#include <atlctrlw.h>
#include <atlctrlx.h>
#include <atlmisc.h>
#include <atlddx.h>
#include <atlcrack.h>
#include <atlscrl.h>
#include <atlprint.h>
#include <atldlgs.h>
#include <atltheme.h>
#include <atlsplit.h>
