/* soapWsWorkunitsServiceSoapProxy.cpp
   Generated by gSOAP 2.7.15 from Services.h
   Copyright(C) 2000-2009, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#include "soapWsWorkunitsServiceSoapProxy.h"

WsWorkunitsServiceSoapProxy::WsWorkunitsServiceSoapProxy()
{	WsWorkunitsServiceSoapProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
}

WsWorkunitsServiceSoapProxy::WsWorkunitsServiceSoapProxy(const struct soap &_soap) :soap(_soap)
{ }

WsWorkunitsServiceSoapProxy::WsWorkunitsServiceSoapProxy(soap_mode iomode)
{	WsWorkunitsServiceSoapProxy_init(iomode, iomode);
}

WsWorkunitsServiceSoapProxy::WsWorkunitsServiceSoapProxy(soap_mode imode, soap_mode omode)
{	WsWorkunitsServiceSoapProxy_init(imode, omode);
}

void WsWorkunitsServiceSoapProxy::WsWorkunitsServiceSoapProxy_init(soap_mode imode, soap_mode omode)
{	soap_imode(this, imode);
	soap_omode(this, omode);
	soap_endpoint = NULL;
	static const struct Namespace namespaces[] =
{
	{"SOAP-ENV", "http://schemas.xmlsoap.org/soap/envelope/", "http://www.w3.org/*/soap-envelope", NULL},
	{"SOAP-ENC", "http://schemas.xmlsoap.org/soap/encoding/", "http://www.w3.org/*/soap-encoding", NULL},
	{"xsi", "http://www.w3.org/2001/XMLSchema-instance", "http://www.w3.org/*/XMLSchema-instance", NULL},
	{"xsd", "http://www.w3.org/2001/XMLSchema", "http://www.w3.org/*/XMLSchema", NULL},
	{"ns1", "http://webservices.seisint.com/ws_account", NULL, NULL},
	{"ns2", "http://webservices.seisint.com/WsAttributes", NULL, NULL},
	{"ns3", "http://webservices.seisint.com/WsDfu", NULL, NULL},
	{"ns4", "http://webservices.seisint.com/WsSMC", NULL, NULL},
	{"ns5", "http://webservices.seisint.com/WsTopology", NULL, NULL},
	{"ns6", "http://webservices.seisint.com/WsWorkunits", NULL, NULL},
	{NULL, NULL, NULL, NULL}
};
	if (!this->namespaces)
		this->namespaces = namespaces;
}

WsWorkunitsServiceSoapProxy::~WsWorkunitsServiceSoapProxy()
{ }

void WsWorkunitsServiceSoapProxy::destroy()
{	soap_destroy(this);
	soap_end(this);
}

void WsWorkunitsServiceSoapProxy::soap_noheader()
{	header = NULL;
}

const SOAP_ENV__Fault *WsWorkunitsServiceSoapProxy::soap_fault()
{	return this->fault;
}

const char *WsWorkunitsServiceSoapProxy::soap_fault_string()
{	return *soap_faultstring(this);
}

const char *WsWorkunitsServiceSoapProxy::soap_fault_detail()
{	return *soap_faultdetail(this);
}

int WsWorkunitsServiceSoapProxy::soap_close_socket()
{	return soap_closesock(this);
}

void WsWorkunitsServiceSoapProxy::soap_print_fault(FILE *fd)
{	::soap_print_fault(this, fd);
}

#ifndef WITH_LEAN
void WsWorkunitsServiceSoapProxy::soap_stream_fault(std::ostream& os)
{	::soap_stream_fault(this, os);
}

char *WsWorkunitsServiceSoapProxy::soap_sprint_fault(char *buf, size_t len)
{	return ::soap_sprint_fault(this, buf, len);
}
#endif

int WsWorkunitsServiceSoapProxy::GVCAjaxGraph(_ns6__GVCAjaxGraph *ns6__GVCAjaxGraph, _ns6__GVCAjaxGraphResponse *ns6__GVCAjaxGraphResponse)
{	struct soap *soap = this;
	struct __ns6__GVCAjaxGraph soap_tmp___ns6__GVCAjaxGraph;
	const char *soap_action = NULL;
	if (!soap_endpoint)
		soap_endpoint = "http://10.173.84.202:8010/WsWorkunits?ver_=1.25";
	soap_action = "WsWorkunits/GVCAjaxGraph?ver_=1.25";
	soap->encodingStyle = NULL;
	soap_tmp___ns6__GVCAjaxGraph.ns6__GVCAjaxGraph = ns6__GVCAjaxGraph;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns6__GVCAjaxGraph(soap, &soap_tmp___ns6__GVCAjaxGraph);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns6__GVCAjaxGraph(soap, &soap_tmp___ns6__GVCAjaxGraph, "-ns6:GVCAjaxGraph", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns6__GVCAjaxGraph(soap, &soap_tmp___ns6__GVCAjaxGraph, "-ns6:GVCAjaxGraph", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns6__GVCAjaxGraphResponse)
		return soap_closesock(soap);
	ns6__GVCAjaxGraphResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns6__GVCAjaxGraphResponse->soap_get(soap, "ns6:GVCAjaxGraphResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int WsWorkunitsServiceSoapProxy::WUAbort(_ns6__WUAbort *ns6__WUAbort, _ns6__WUAbortResponse *ns6__WUAbortResponse)
{	struct soap *soap = this;
	struct __ns6__WUAbort soap_tmp___ns6__WUAbort;
	const char *soap_action = NULL;
	if (!soap_endpoint)
		soap_endpoint = "http://10.173.84.202:8010/WsWorkunits?ver_=1.25";
	soap_action = "WsWorkunits/WUAbort?ver_=1.25";
	soap->encodingStyle = NULL;
	soap_tmp___ns6__WUAbort.ns6__WUAbort = ns6__WUAbort;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns6__WUAbort(soap, &soap_tmp___ns6__WUAbort);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns6__WUAbort(soap, &soap_tmp___ns6__WUAbort, "-ns6:WUAbort", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns6__WUAbort(soap, &soap_tmp___ns6__WUAbort, "-ns6:WUAbort", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns6__WUAbortResponse)
		return soap_closesock(soap);
	ns6__WUAbortResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns6__WUAbortResponse->soap_get(soap, "ns6:WUAbortResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int WsWorkunitsServiceSoapProxy::WUAction(_ns6__WUAction *ns6__WUAction, _ns6__WUActionResponse *ns6__WUActionResponse)
{	struct soap *soap = this;
	struct __ns6__WUAction soap_tmp___ns6__WUAction;
	const char *soap_action = NULL;
	if (!soap_endpoint)
		soap_endpoint = "http://10.173.84.202:8010/WsWorkunits?ver_=1.25";
	soap_action = "WsWorkunits/WUAction?ver_=1.25";
	soap->encodingStyle = NULL;
	soap_tmp___ns6__WUAction.ns6__WUAction = ns6__WUAction;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns6__WUAction(soap, &soap_tmp___ns6__WUAction);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns6__WUAction(soap, &soap_tmp___ns6__WUAction, "-ns6:WUAction", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns6__WUAction(soap, &soap_tmp___ns6__WUAction, "-ns6:WUAction", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns6__WUActionResponse)
		return soap_closesock(soap);
	ns6__WUActionResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns6__WUActionResponse->soap_get(soap, "ns6:WUActionResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int WsWorkunitsServiceSoapProxy::WUAddLocalFileToWorkunit(_ns6__WUAddLocalFileToWorkunit *ns6__WUAddLocalFileToWorkunit, _ns6__WUAddLocalFileToWorkunitResponse *ns6__WUAddLocalFileToWorkunitResponse)
{	struct soap *soap = this;
	struct __ns6__WUAddLocalFileToWorkunit soap_tmp___ns6__WUAddLocalFileToWorkunit;
	const char *soap_action = NULL;
	if (!soap_endpoint)
		soap_endpoint = "http://10.173.84.202:8010/WsWorkunits?ver_=1.25";
	soap_action = "WsWorkunits/WUAddLocalFileToWorkunit?ver_=1.25";
	soap->encodingStyle = NULL;
	soap_tmp___ns6__WUAddLocalFileToWorkunit.ns6__WUAddLocalFileToWorkunit = ns6__WUAddLocalFileToWorkunit;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns6__WUAddLocalFileToWorkunit(soap, &soap_tmp___ns6__WUAddLocalFileToWorkunit);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns6__WUAddLocalFileToWorkunit(soap, &soap_tmp___ns6__WUAddLocalFileToWorkunit, "-ns6:WUAddLocalFileToWorkunit", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns6__WUAddLocalFileToWorkunit(soap, &soap_tmp___ns6__WUAddLocalFileToWorkunit, "-ns6:WUAddLocalFileToWorkunit", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns6__WUAddLocalFileToWorkunitResponse)
		return soap_closesock(soap);
	ns6__WUAddLocalFileToWorkunitResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns6__WUAddLocalFileToWorkunitResponse->soap_get(soap, "ns6:WUAddLocalFileToWorkunitResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int WsWorkunitsServiceSoapProxy::WUCDebug(_ns6__WUCDebug *ns6__WUCDebug, _ns6__WUDebugResponse *ns6__WUDebugResponse)
{	struct soap *soap = this;
	struct __ns6__WUCDebug soap_tmp___ns6__WUCDebug;
	const char *soap_action = NULL;
	if (!soap_endpoint)
		soap_endpoint = "http://10.173.84.202:8010/WsWorkunits?ver_=1.25";
	soap_action = "WsWorkunits/WUCDebug?ver_=1.25";
	soap->encodingStyle = NULL;
	soap_tmp___ns6__WUCDebug.ns6__WUCDebug = ns6__WUCDebug;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns6__WUCDebug(soap, &soap_tmp___ns6__WUCDebug);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns6__WUCDebug(soap, &soap_tmp___ns6__WUCDebug, "-ns6:WUCDebug", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns6__WUCDebug(soap, &soap_tmp___ns6__WUCDebug, "-ns6:WUCDebug", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns6__WUDebugResponse)
		return soap_closesock(soap);
	ns6__WUDebugResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns6__WUDebugResponse->soap_get(soap, "ns6:WUDebugResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int WsWorkunitsServiceSoapProxy::WUClusterJobQueueLOG(_ns6__WUClusterJobQueueLOG *ns6__WUClusterJobQueueLOG, _ns6__WUClusterJobQueueLOGResponse *ns6__WUClusterJobQueueLOGResponse)
{	struct soap *soap = this;
	struct __ns6__WUClusterJobQueueLOG soap_tmp___ns6__WUClusterJobQueueLOG;
	const char *soap_action = NULL;
	if (!soap_endpoint)
		soap_endpoint = "http://10.173.84.202:8010/WsWorkunits?ver_=1.25";
	soap_action = "WsWorkunits/WUClusterJobQueueLOG?ver_=1.25";
	soap->encodingStyle = NULL;
	soap_tmp___ns6__WUClusterJobQueueLOG.ns6__WUClusterJobQueueLOG = ns6__WUClusterJobQueueLOG;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns6__WUClusterJobQueueLOG(soap, &soap_tmp___ns6__WUClusterJobQueueLOG);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns6__WUClusterJobQueueLOG(soap, &soap_tmp___ns6__WUClusterJobQueueLOG, "-ns6:WUClusterJobQueueLOG", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns6__WUClusterJobQueueLOG(soap, &soap_tmp___ns6__WUClusterJobQueueLOG, "-ns6:WUClusterJobQueueLOG", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns6__WUClusterJobQueueLOGResponse)
		return soap_closesock(soap);
	ns6__WUClusterJobQueueLOGResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns6__WUClusterJobQueueLOGResponse->soap_get(soap, "ns6:WUClusterJobQueueLOGResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int WsWorkunitsServiceSoapProxy::WUClusterJobQueueXLS(_ns6__WUClusterJobQueueXLS *ns6__WUClusterJobQueueXLS, _ns6__WUClusterJobQueueXLSResponse *ns6__WUClusterJobQueueXLSResponse)
{	struct soap *soap = this;
	struct __ns6__WUClusterJobQueueXLS soap_tmp___ns6__WUClusterJobQueueXLS;
	const char *soap_action = NULL;
	if (!soap_endpoint)
		soap_endpoint = "http://10.173.84.202:8010/WsWorkunits?ver_=1.25";
	soap_action = "WsWorkunits/WUClusterJobQueueXLS?ver_=1.25";
	soap->encodingStyle = NULL;
	soap_tmp___ns6__WUClusterJobQueueXLS.ns6__WUClusterJobQueueXLS = ns6__WUClusterJobQueueXLS;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns6__WUClusterJobQueueXLS(soap, &soap_tmp___ns6__WUClusterJobQueueXLS);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns6__WUClusterJobQueueXLS(soap, &soap_tmp___ns6__WUClusterJobQueueXLS, "-ns6:WUClusterJobQueueXLS", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns6__WUClusterJobQueueXLS(soap, &soap_tmp___ns6__WUClusterJobQueueXLS, "-ns6:WUClusterJobQueueXLS", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns6__WUClusterJobQueueXLSResponse)
		return soap_closesock(soap);
	ns6__WUClusterJobQueueXLSResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns6__WUClusterJobQueueXLSResponse->soap_get(soap, "ns6:WUClusterJobQueueXLSResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int WsWorkunitsServiceSoapProxy::WUClusterJobSummaryXLS(_ns6__WUClusterJobSummaryXLS *ns6__WUClusterJobSummaryXLS, _ns6__WUClusterJobSummaryXLSResponse *ns6__WUClusterJobSummaryXLSResponse)
{	struct soap *soap = this;
	struct __ns6__WUClusterJobSummaryXLS soap_tmp___ns6__WUClusterJobSummaryXLS;
	const char *soap_action = NULL;
	if (!soap_endpoint)
		soap_endpoint = "http://10.173.84.202:8010/WsWorkunits?ver_=1.25";
	soap_action = "WsWorkunits/WUClusterJobSummaryXLS?ver_=1.25";
	soap->encodingStyle = NULL;
	soap_tmp___ns6__WUClusterJobSummaryXLS.ns6__WUClusterJobSummaryXLS = ns6__WUClusterJobSummaryXLS;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns6__WUClusterJobSummaryXLS(soap, &soap_tmp___ns6__WUClusterJobSummaryXLS);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns6__WUClusterJobSummaryXLS(soap, &soap_tmp___ns6__WUClusterJobSummaryXLS, "-ns6:WUClusterJobSummaryXLS", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns6__WUClusterJobSummaryXLS(soap, &soap_tmp___ns6__WUClusterJobSummaryXLS, "-ns6:WUClusterJobSummaryXLS", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns6__WUClusterJobSummaryXLSResponse)
		return soap_closesock(soap);
	ns6__WUClusterJobSummaryXLSResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns6__WUClusterJobSummaryXLSResponse->soap_get(soap, "ns6:WUClusterJobSummaryXLSResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int WsWorkunitsServiceSoapProxy::WUClusterJobXLS(_ns6__WUClusterJobXLS *ns6__WUClusterJobXLS, _ns6__WUClusterJobXLSResponse *ns6__WUClusterJobXLSResponse)
{	struct soap *soap = this;
	struct __ns6__WUClusterJobXLS soap_tmp___ns6__WUClusterJobXLS;
	const char *soap_action = NULL;
	if (!soap_endpoint)
		soap_endpoint = "http://10.173.84.202:8010/WsWorkunits?ver_=1.25";
	soap_action = "WsWorkunits/WUClusterJobXLS?ver_=1.25";
	soap->encodingStyle = NULL;
	soap_tmp___ns6__WUClusterJobXLS.ns6__WUClusterJobXLS = ns6__WUClusterJobXLS;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns6__WUClusterJobXLS(soap, &soap_tmp___ns6__WUClusterJobXLS);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns6__WUClusterJobXLS(soap, &soap_tmp___ns6__WUClusterJobXLS, "-ns6:WUClusterJobXLS", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns6__WUClusterJobXLS(soap, &soap_tmp___ns6__WUClusterJobXLS, "-ns6:WUClusterJobXLS", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns6__WUClusterJobXLSResponse)
		return soap_closesock(soap);
	ns6__WUClusterJobXLSResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns6__WUClusterJobXLSResponse->soap_get(soap, "ns6:WUClusterJobXLSResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int WsWorkunitsServiceSoapProxy::WUCompileECL(_ns6__WUCompileECL *ns6__WUCompileECL, _ns6__WUCompileECLResponse *ns6__WUCompileECLResponse)
{	struct soap *soap = this;
	struct __ns6__WUCompileECL soap_tmp___ns6__WUCompileECL;
	const char *soap_action = NULL;
	if (!soap_endpoint)
		soap_endpoint = "http://10.173.84.202:8010/WsWorkunits?ver_=1.25";
	soap_action = "WsWorkunits/WUCompileECL?ver_=1.25";
	soap->encodingStyle = NULL;
	soap_tmp___ns6__WUCompileECL.ns6__WUCompileECL = ns6__WUCompileECL;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns6__WUCompileECL(soap, &soap_tmp___ns6__WUCompileECL);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns6__WUCompileECL(soap, &soap_tmp___ns6__WUCompileECL, "-ns6:WUCompileECL", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns6__WUCompileECL(soap, &soap_tmp___ns6__WUCompileECL, "-ns6:WUCompileECL", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns6__WUCompileECLResponse)
		return soap_closesock(soap);
	ns6__WUCompileECLResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns6__WUCompileECLResponse->soap_get(soap, "ns6:WUCompileECLResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int WsWorkunitsServiceSoapProxy::WUCreate(_ns6__WUCreate *ns6__WUCreate, _ns6__WUCreateResponse *ns6__WUCreateResponse)
{	struct soap *soap = this;
	struct __ns6__WUCreate soap_tmp___ns6__WUCreate;
	const char *soap_action = NULL;
	if (!soap_endpoint)
		soap_endpoint = "http://10.173.84.202:8010/WsWorkunits?ver_=1.25";
	soap_action = "WsWorkunits/WUCreate?ver_=1.25";
	soap->encodingStyle = NULL;
	soap_tmp___ns6__WUCreate.ns6__WUCreate = ns6__WUCreate;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns6__WUCreate(soap, &soap_tmp___ns6__WUCreate);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns6__WUCreate(soap, &soap_tmp___ns6__WUCreate, "-ns6:WUCreate", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns6__WUCreate(soap, &soap_tmp___ns6__WUCreate, "-ns6:WUCreate", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns6__WUCreateResponse)
		return soap_closesock(soap);
	ns6__WUCreateResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns6__WUCreateResponse->soap_get(soap, "ns6:WUCreateResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int WsWorkunitsServiceSoapProxy::WUCreateAndUpdate(_ns6__WUCreateAndUpdate *ns6__WUCreateAndUpdate, _ns6__WUUpdateResponse *ns6__WUUpdateResponse)
{	struct soap *soap = this;
	struct __ns6__WUCreateAndUpdate soap_tmp___ns6__WUCreateAndUpdate;
	const char *soap_action = NULL;
	if (!soap_endpoint)
		soap_endpoint = "http://10.173.84.202:8010/WsWorkunits?ver_=1.25";
	soap_action = "WsWorkunits/WUCreateAndUpdate?ver_=1.25";
	soap->encodingStyle = NULL;
	soap_tmp___ns6__WUCreateAndUpdate.ns6__WUCreateAndUpdate = ns6__WUCreateAndUpdate;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns6__WUCreateAndUpdate(soap, &soap_tmp___ns6__WUCreateAndUpdate);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns6__WUCreateAndUpdate(soap, &soap_tmp___ns6__WUCreateAndUpdate, "-ns6:WUCreateAndUpdate", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns6__WUCreateAndUpdate(soap, &soap_tmp___ns6__WUCreateAndUpdate, "-ns6:WUCreateAndUpdate", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns6__WUUpdateResponse)
		return soap_closesock(soap);
	ns6__WUUpdateResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns6__WUUpdateResponse->soap_get(soap, "ns6:WUUpdateResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int WsWorkunitsServiceSoapProxy::WUDelete(_ns6__WUDelete *ns6__WUDelete, _ns6__WUDeleteResponse *ns6__WUDeleteResponse)
{	struct soap *soap = this;
	struct __ns6__WUDelete soap_tmp___ns6__WUDelete;
	const char *soap_action = NULL;
	if (!soap_endpoint)
		soap_endpoint = "http://10.173.84.202:8010/WsWorkunits?ver_=1.25";
	soap_action = "WsWorkunits/WUDelete?ver_=1.25";
	soap->encodingStyle = NULL;
	soap_tmp___ns6__WUDelete.ns6__WUDelete = ns6__WUDelete;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns6__WUDelete(soap, &soap_tmp___ns6__WUDelete);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns6__WUDelete(soap, &soap_tmp___ns6__WUDelete, "-ns6:WUDelete", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns6__WUDelete(soap, &soap_tmp___ns6__WUDelete, "-ns6:WUDelete", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns6__WUDeleteResponse)
		return soap_closesock(soap);
	ns6__WUDeleteResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns6__WUDeleteResponse->soap_get(soap, "ns6:WUDeleteResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int WsWorkunitsServiceSoapProxy::WUExport(_ns6__WUExport *ns6__WUExport, _ns6__WUExportResponse *ns6__WUExportResponse)
{	struct soap *soap = this;
	struct __ns6__WUExport soap_tmp___ns6__WUExport;
	const char *soap_action = NULL;
	if (!soap_endpoint)
		soap_endpoint = "http://10.173.84.202:8010/WsWorkunits?ver_=1.25";
	soap_action = "WsWorkunits/WUExport?ver_=1.25";
	soap->encodingStyle = NULL;
	soap_tmp___ns6__WUExport.ns6__WUExport = ns6__WUExport;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns6__WUExport(soap, &soap_tmp___ns6__WUExport);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns6__WUExport(soap, &soap_tmp___ns6__WUExport, "-ns6:WUExport", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns6__WUExport(soap, &soap_tmp___ns6__WUExport, "-ns6:WUExport", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns6__WUExportResponse)
		return soap_closesock(soap);
	ns6__WUExportResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns6__WUExportResponse->soap_get(soap, "ns6:WUExportResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int WsWorkunitsServiceSoapProxy::WUFile(_ns6__WUFile *ns6__WUFile, _ns6__WULogFileResponse *ns6__WULogFileResponse)
{	struct soap *soap = this;
	struct __ns6__WUFile soap_tmp___ns6__WUFile;
	const char *soap_action = NULL;
	if (!soap_endpoint)
		soap_endpoint = "http://10.173.84.202:8010/WsWorkunits?ver_=1.25";
	soap_action = "WsWorkunits/WUFile?ver_=1.25";
	soap->encodingStyle = NULL;
	soap_tmp___ns6__WUFile.ns6__WUFile = ns6__WUFile;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns6__WUFile(soap, &soap_tmp___ns6__WUFile);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns6__WUFile(soap, &soap_tmp___ns6__WUFile, "-ns6:WUFile", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns6__WUFile(soap, &soap_tmp___ns6__WUFile, "-ns6:WUFile", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns6__WULogFileResponse)
		return soap_closesock(soap);
	ns6__WULogFileResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns6__WULogFileResponse->soap_get(soap, "ns6:WULogFileResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int WsWorkunitsServiceSoapProxy::WUGVCGraphInfo(_ns6__WUGVCGraphInfo *ns6__WUGVCGraphInfo, _ns6__WUGVCGraphInfoResponse *ns6__WUGVCGraphInfoResponse)
{	struct soap *soap = this;
	struct __ns6__WUGVCGraphInfo soap_tmp___ns6__WUGVCGraphInfo;
	const char *soap_action = NULL;
	if (!soap_endpoint)
		soap_endpoint = "http://10.173.84.202:8010/WsWorkunits?ver_=1.25";
	soap_action = "WsWorkunits/WUGVCGraphInfo?ver_=1.25";
	soap->encodingStyle = NULL;
	soap_tmp___ns6__WUGVCGraphInfo.ns6__WUGVCGraphInfo = ns6__WUGVCGraphInfo;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns6__WUGVCGraphInfo(soap, &soap_tmp___ns6__WUGVCGraphInfo);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns6__WUGVCGraphInfo(soap, &soap_tmp___ns6__WUGVCGraphInfo, "-ns6:WUGVCGraphInfo", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns6__WUGVCGraphInfo(soap, &soap_tmp___ns6__WUGVCGraphInfo, "-ns6:WUGVCGraphInfo", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns6__WUGVCGraphInfoResponse)
		return soap_closesock(soap);
	ns6__WUGVCGraphInfoResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns6__WUGVCGraphInfoResponse->soap_get(soap, "ns6:WUGVCGraphInfoResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int WsWorkunitsServiceSoapProxy::WUGetDependancyTrees(_ns6__WUGetDependancyTrees *ns6__WUGetDependancyTrees, _ns6__WUGetDependancyTreesResponse *ns6__WUGetDependancyTreesResponse)
{	struct soap *soap = this;
	struct __ns6__WUGetDependancyTrees soap_tmp___ns6__WUGetDependancyTrees;
	const char *soap_action = NULL;
	if (!soap_endpoint)
		soap_endpoint = "http://10.173.84.202:8010/WsWorkunits?ver_=1.25";
	soap_action = "WsWorkunits/WUGetDependancyTrees?ver_=1.25";
	soap->encodingStyle = NULL;
	soap_tmp___ns6__WUGetDependancyTrees.ns6__WUGetDependancyTrees = ns6__WUGetDependancyTrees;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns6__WUGetDependancyTrees(soap, &soap_tmp___ns6__WUGetDependancyTrees);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns6__WUGetDependancyTrees(soap, &soap_tmp___ns6__WUGetDependancyTrees, "-ns6:WUGetDependancyTrees", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns6__WUGetDependancyTrees(soap, &soap_tmp___ns6__WUGetDependancyTrees, "-ns6:WUGetDependancyTrees", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns6__WUGetDependancyTreesResponse)
		return soap_closesock(soap);
	ns6__WUGetDependancyTreesResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns6__WUGetDependancyTreesResponse->soap_get(soap, "ns6:WUGetDependancyTreesResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int WsWorkunitsServiceSoapProxy::WUGetGraph(_ns6__WUGetGraph *ns6__WUGetGraph, _ns6__WUGetGraphResponse *ns6__WUGetGraphResponse)
{	struct soap *soap = this;
	struct __ns6__WUGetGraph soap_tmp___ns6__WUGetGraph;
	const char *soap_action = NULL;
	if (!soap_endpoint)
		soap_endpoint = "http://10.173.84.202:8010/WsWorkunits?ver_=1.25";
	soap_action = "WsWorkunits/WUGetGraph?ver_=1.25";
	soap->encodingStyle = NULL;
	soap_tmp___ns6__WUGetGraph.ns6__WUGetGraph = ns6__WUGetGraph;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns6__WUGetGraph(soap, &soap_tmp___ns6__WUGetGraph);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns6__WUGetGraph(soap, &soap_tmp___ns6__WUGetGraph, "-ns6:WUGetGraph", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns6__WUGetGraph(soap, &soap_tmp___ns6__WUGetGraph, "-ns6:WUGetGraph", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns6__WUGetGraphResponse)
		return soap_closesock(soap);
	ns6__WUGetGraphResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns6__WUGetGraphResponse->soap_get(soap, "ns6:WUGetGraphResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int WsWorkunitsServiceSoapProxy::WUGraphInfo(_ns6__WUGraphInfo *ns6__WUGraphInfo, _ns6__WUGraphInfoResponse *ns6__WUGraphInfoResponse)
{	struct soap *soap = this;
	struct __ns6__WUGraphInfo soap_tmp___ns6__WUGraphInfo;
	const char *soap_action = NULL;
	if (!soap_endpoint)
		soap_endpoint = "http://10.173.84.202:8010/WsWorkunits?ver_=1.25";
	soap_action = "WsWorkunits/WUGraphInfo?ver_=1.25";
	soap->encodingStyle = NULL;
	soap_tmp___ns6__WUGraphInfo.ns6__WUGraphInfo = ns6__WUGraphInfo;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns6__WUGraphInfo(soap, &soap_tmp___ns6__WUGraphInfo);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns6__WUGraphInfo(soap, &soap_tmp___ns6__WUGraphInfo, "-ns6:WUGraphInfo", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns6__WUGraphInfo(soap, &soap_tmp___ns6__WUGraphInfo, "-ns6:WUGraphInfo", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns6__WUGraphInfoResponse)
		return soap_closesock(soap);
	ns6__WUGraphInfoResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns6__WUGraphInfoResponse->soap_get(soap, "ns6:WUGraphInfoResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int WsWorkunitsServiceSoapProxy::WUGraphTiming(_ns6__WUGraphTiming *ns6__WUGraphTiming, _ns6__WUGraphTimingResponse *ns6__WUGraphTimingResponse)
{	struct soap *soap = this;
	struct __ns6__WUGraphTiming soap_tmp___ns6__WUGraphTiming;
	const char *soap_action = NULL;
	if (!soap_endpoint)
		soap_endpoint = "http://10.173.84.202:8010/WsWorkunits?ver_=1.25";
	soap_action = "WsWorkunits/WUGraphTiming?ver_=1.25";
	soap->encodingStyle = NULL;
	soap_tmp___ns6__WUGraphTiming.ns6__WUGraphTiming = ns6__WUGraphTiming;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns6__WUGraphTiming(soap, &soap_tmp___ns6__WUGraphTiming);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns6__WUGraphTiming(soap, &soap_tmp___ns6__WUGraphTiming, "-ns6:WUGraphTiming", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns6__WUGraphTiming(soap, &soap_tmp___ns6__WUGraphTiming, "-ns6:WUGraphTiming", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns6__WUGraphTimingResponse)
		return soap_closesock(soap);
	ns6__WUGraphTimingResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns6__WUGraphTimingResponse->soap_get(soap, "ns6:WUGraphTimingResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int WsWorkunitsServiceSoapProxy::WUInfo(_ns6__WUInfo *ns6__WUInfo, _ns6__WUInfoResponse *ns6__WUInfoResponse)
{	struct soap *soap = this;
	struct __ns6__WUInfo soap_tmp___ns6__WUInfo;
	const char *soap_action = NULL;
	if (!soap_endpoint)
		soap_endpoint = "http://10.173.84.202:8010/WsWorkunits?ver_=1.25";
	soap_action = "WsWorkunits/WUInfo?ver_=1.25";
	soap->encodingStyle = NULL;
	soap_tmp___ns6__WUInfo.ns6__WUInfo = ns6__WUInfo;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns6__WUInfo(soap, &soap_tmp___ns6__WUInfo);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns6__WUInfo(soap, &soap_tmp___ns6__WUInfo, "-ns6:WUInfo", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns6__WUInfo(soap, &soap_tmp___ns6__WUInfo, "-ns6:WUInfo", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns6__WUInfoResponse)
		return soap_closesock(soap);
	ns6__WUInfoResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns6__WUInfoResponse->soap_get(soap, "ns6:WUInfoResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int WsWorkunitsServiceSoapProxy::WUInfoDetails(_ns6__WUInfoDetails *ns6__WUInfoDetails, _ns6__WUInfoResponse *ns6__WUInfoResponse)
{	struct soap *soap = this;
	struct __ns6__WUInfoDetails soap_tmp___ns6__WUInfoDetails;
	const char *soap_action = NULL;
	if (!soap_endpoint)
		soap_endpoint = "http://10.173.84.202:8010/WsWorkunits?ver_=1.25";
	soap_action = "WsWorkunits/WUInfoDetails?ver_=1.25";
	soap->encodingStyle = NULL;
	soap_tmp___ns6__WUInfoDetails.ns6__WUInfoDetails = ns6__WUInfoDetails;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns6__WUInfoDetails(soap, &soap_tmp___ns6__WUInfoDetails);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns6__WUInfoDetails(soap, &soap_tmp___ns6__WUInfoDetails, "-ns6:WUInfoDetails", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns6__WUInfoDetails(soap, &soap_tmp___ns6__WUInfoDetails, "-ns6:WUInfoDetails", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns6__WUInfoResponse)
		return soap_closesock(soap);
	ns6__WUInfoResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns6__WUInfoResponse->soap_get(soap, "ns6:WUInfoResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int WsWorkunitsServiceSoapProxy::WUJobList(_ns6__WUJobList *ns6__WUJobList, _ns6__WUJobListResponse *ns6__WUJobListResponse)
{	struct soap *soap = this;
	struct __ns6__WUJobList soap_tmp___ns6__WUJobList;
	const char *soap_action = NULL;
	if (!soap_endpoint)
		soap_endpoint = "http://10.173.84.202:8010/WsWorkunits?ver_=1.25";
	soap_action = "WsWorkunits/WUJobList?ver_=1.25";
	soap->encodingStyle = NULL;
	soap_tmp___ns6__WUJobList.ns6__WUJobList = ns6__WUJobList;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns6__WUJobList(soap, &soap_tmp___ns6__WUJobList);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns6__WUJobList(soap, &soap_tmp___ns6__WUJobList, "-ns6:WUJobList", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns6__WUJobList(soap, &soap_tmp___ns6__WUJobList, "-ns6:WUJobList", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns6__WUJobListResponse)
		return soap_closesock(soap);
	ns6__WUJobListResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns6__WUJobListResponse->soap_get(soap, "ns6:WUJobListResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int WsWorkunitsServiceSoapProxy::WUListLocalFileRequired(_ns6__WUListLocalFileRequired *ns6__WUListLocalFileRequired, _ns6__WUListLocalFileRequiredResponse *ns6__WUListLocalFileRequiredResponse)
{	struct soap *soap = this;
	struct __ns6__WUListLocalFileRequired soap_tmp___ns6__WUListLocalFileRequired;
	const char *soap_action = NULL;
	if (!soap_endpoint)
		soap_endpoint = "http://10.173.84.202:8010/WsWorkunits?ver_=1.25";
	soap_action = "WsWorkunits/WUListLocalFileRequired?ver_=1.25";
	soap->encodingStyle = NULL;
	soap_tmp___ns6__WUListLocalFileRequired.ns6__WUListLocalFileRequired = ns6__WUListLocalFileRequired;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns6__WUListLocalFileRequired(soap, &soap_tmp___ns6__WUListLocalFileRequired);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns6__WUListLocalFileRequired(soap, &soap_tmp___ns6__WUListLocalFileRequired, "-ns6:WUListLocalFileRequired", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns6__WUListLocalFileRequired(soap, &soap_tmp___ns6__WUListLocalFileRequired, "-ns6:WUListLocalFileRequired", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns6__WUListLocalFileRequiredResponse)
		return soap_closesock(soap);
	ns6__WUListLocalFileRequiredResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns6__WUListLocalFileRequiredResponse->soap_get(soap, "ns6:WUListLocalFileRequiredResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int WsWorkunitsServiceSoapProxy::WUProcessGraph(_ns6__WUProcessGraph *ns6__WUProcessGraph, _ns6__WUProcessGraphResponse *ns6__WUProcessGraphResponse)
{	struct soap *soap = this;
	struct __ns6__WUProcessGraph soap_tmp___ns6__WUProcessGraph;
	const char *soap_action = NULL;
	if (!soap_endpoint)
		soap_endpoint = "http://10.173.84.202:8010/WsWorkunits?ver_=1.25";
	soap_action = "WsWorkunits/WUProcessGraph?ver_=1.25";
	soap->encodingStyle = NULL;
	soap_tmp___ns6__WUProcessGraph.ns6__WUProcessGraph = ns6__WUProcessGraph;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns6__WUProcessGraph(soap, &soap_tmp___ns6__WUProcessGraph);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns6__WUProcessGraph(soap, &soap_tmp___ns6__WUProcessGraph, "-ns6:WUProcessGraph", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns6__WUProcessGraph(soap, &soap_tmp___ns6__WUProcessGraph, "-ns6:WUProcessGraph", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns6__WUProcessGraphResponse)
		return soap_closesock(soap);
	ns6__WUProcessGraphResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns6__WUProcessGraphResponse->soap_get(soap, "ns6:WUProcessGraphResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int WsWorkunitsServiceSoapProxy::WUProtect(_ns6__WUProtect *ns6__WUProtect, _ns6__WUProtectResponse *ns6__WUProtectResponse)
{	struct soap *soap = this;
	struct __ns6__WUProtect soap_tmp___ns6__WUProtect;
	const char *soap_action = NULL;
	if (!soap_endpoint)
		soap_endpoint = "http://10.173.84.202:8010/WsWorkunits?ver_=1.25";
	soap_action = "WsWorkunits/WUProtect?ver_=1.25";
	soap->encodingStyle = NULL;
	soap_tmp___ns6__WUProtect.ns6__WUProtect = ns6__WUProtect;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns6__WUProtect(soap, &soap_tmp___ns6__WUProtect);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns6__WUProtect(soap, &soap_tmp___ns6__WUProtect, "-ns6:WUProtect", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns6__WUProtect(soap, &soap_tmp___ns6__WUProtect, "-ns6:WUProtect", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns6__WUProtectResponse)
		return soap_closesock(soap);
	ns6__WUProtectResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns6__WUProtectResponse->soap_get(soap, "ns6:WUProtectResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int WsWorkunitsServiceSoapProxy::WUPushEvent(_ns6__WUPushEvent *ns6__WUPushEvent, _ns6__WUPushEventResponse *ns6__WUPushEventResponse)
{	struct soap *soap = this;
	struct __ns6__WUPushEvent soap_tmp___ns6__WUPushEvent;
	const char *soap_action = NULL;
	if (!soap_endpoint)
		soap_endpoint = "http://10.173.84.202:8010/WsWorkunits?ver_=1.25";
	soap_action = "WsWorkunits/WUPushEvent?ver_=1.25";
	soap->encodingStyle = NULL;
	soap_tmp___ns6__WUPushEvent.ns6__WUPushEvent = ns6__WUPushEvent;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns6__WUPushEvent(soap, &soap_tmp___ns6__WUPushEvent);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns6__WUPushEvent(soap, &soap_tmp___ns6__WUPushEvent, "-ns6:WUPushEvent", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns6__WUPushEvent(soap, &soap_tmp___ns6__WUPushEvent, "-ns6:WUPushEvent", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns6__WUPushEventResponse)
		return soap_closesock(soap);
	ns6__WUPushEventResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns6__WUPushEventResponse->soap_get(soap, "ns6:WUPushEventResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int WsWorkunitsServiceSoapProxy::WUQuery(_ns6__WUQuery *ns6__WUQuery, _ns6__WUQueryResponse *ns6__WUQueryResponse)
{	struct soap *soap = this;
	struct __ns6__WUQuery soap_tmp___ns6__WUQuery;
	const char *soap_action = NULL;
	if (!soap_endpoint)
		soap_endpoint = "http://10.173.84.202:8010/WsWorkunits?ver_=1.25";
	soap_action = "WsWorkunits/WUQuery?ver_=1.25";
	soap->encodingStyle = NULL;
	soap_tmp___ns6__WUQuery.ns6__WUQuery = ns6__WUQuery;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns6__WUQuery(soap, &soap_tmp___ns6__WUQuery);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns6__WUQuery(soap, &soap_tmp___ns6__WUQuery, "-ns6:WUQuery", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns6__WUQuery(soap, &soap_tmp___ns6__WUQuery, "-ns6:WUQuery", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns6__WUQueryResponse)
		return soap_closesock(soap);
	ns6__WUQueryResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns6__WUQueryResponse->soap_get(soap, "ns6:WUQueryResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int WsWorkunitsServiceSoapProxy::WUResubmit(_ns6__WUResubmit *ns6__WUResubmit, _ns6__WUResubmitResponse *ns6__WUResubmitResponse)
{	struct soap *soap = this;
	struct __ns6__WUResubmit soap_tmp___ns6__WUResubmit;
	const char *soap_action = NULL;
	if (!soap_endpoint)
		soap_endpoint = "http://10.173.84.202:8010/WsWorkunits?ver_=1.25";
	soap_action = "WsWorkunits/WUResubmit?ver_=1.25";
	soap->encodingStyle = NULL;
	soap_tmp___ns6__WUResubmit.ns6__WUResubmit = ns6__WUResubmit;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns6__WUResubmit(soap, &soap_tmp___ns6__WUResubmit);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns6__WUResubmit(soap, &soap_tmp___ns6__WUResubmit, "-ns6:WUResubmit", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns6__WUResubmit(soap, &soap_tmp___ns6__WUResubmit, "-ns6:WUResubmit", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns6__WUResubmitResponse)
		return soap_closesock(soap);
	ns6__WUResubmitResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns6__WUResubmitResponse->soap_get(soap, "ns6:WUResubmitResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int WsWorkunitsServiceSoapProxy::WUResult(_ns6__WUResult *ns6__WUResult, _ns6__WUResultResponse *ns6__WUResultResponse)
{	struct soap *soap = this;
	struct __ns6__WUResult soap_tmp___ns6__WUResult;
	const char *soap_action = NULL;
	if (!soap_endpoint)
		soap_endpoint = "http://10.173.84.202:8010/WsWorkunits?ver_=1.25";
	soap_action = "WsWorkunits/WUResult?ver_=1.25";
	soap->encodingStyle = NULL;
	soap_tmp___ns6__WUResult.ns6__WUResult = ns6__WUResult;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns6__WUResult(soap, &soap_tmp___ns6__WUResult);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns6__WUResult(soap, &soap_tmp___ns6__WUResult, "-ns6:WUResult", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns6__WUResult(soap, &soap_tmp___ns6__WUResult, "-ns6:WUResult", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns6__WUResultResponse)
		return soap_closesock(soap);
	ns6__WUResultResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns6__WUResultResponse->soap_get(soap, "ns6:WUResultResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int WsWorkunitsServiceSoapProxy::WUResultBin(_ns6__WUResultBin *ns6__WUResultBin, _ns6__WUResultBinResponse *ns6__WUResultBinResponse)
{	struct soap *soap = this;
	struct __ns6__WUResultBin soap_tmp___ns6__WUResultBin;
	const char *soap_action = NULL;
	if (!soap_endpoint)
		soap_endpoint = "http://10.173.84.202:8010/WsWorkunits?ver_=1.25";
	soap_action = "WsWorkunits/WUResultBin?ver_=1.25";
	soap->encodingStyle = NULL;
	soap_tmp___ns6__WUResultBin.ns6__WUResultBin = ns6__WUResultBin;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns6__WUResultBin(soap, &soap_tmp___ns6__WUResultBin);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns6__WUResultBin(soap, &soap_tmp___ns6__WUResultBin, "-ns6:WUResultBin", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns6__WUResultBin(soap, &soap_tmp___ns6__WUResultBin, "-ns6:WUResultBin", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns6__WUResultBinResponse)
		return soap_closesock(soap);
	ns6__WUResultBinResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns6__WUResultBinResponse->soap_get(soap, "ns6:WUResultBinResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int WsWorkunitsServiceSoapProxy::WUResultSummary(_ns6__WUResultSummary *ns6__WUResultSummary, _ns6__WUResultSummaryResponse *ns6__WUResultSummaryResponse)
{	struct soap *soap = this;
	struct __ns6__WUResultSummary soap_tmp___ns6__WUResultSummary;
	const char *soap_action = NULL;
	if (!soap_endpoint)
		soap_endpoint = "http://10.173.84.202:8010/WsWorkunits?ver_=1.25";
	soap_action = "WsWorkunits/WUResultSummary?ver_=1.25";
	soap->encodingStyle = NULL;
	soap_tmp___ns6__WUResultSummary.ns6__WUResultSummary = ns6__WUResultSummary;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns6__WUResultSummary(soap, &soap_tmp___ns6__WUResultSummary);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns6__WUResultSummary(soap, &soap_tmp___ns6__WUResultSummary, "-ns6:WUResultSummary", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns6__WUResultSummary(soap, &soap_tmp___ns6__WUResultSummary, "-ns6:WUResultSummary", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns6__WUResultSummaryResponse)
		return soap_closesock(soap);
	ns6__WUResultSummaryResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns6__WUResultSummaryResponse->soap_get(soap, "ns6:WUResultSummaryResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int WsWorkunitsServiceSoapProxy::WUSchedule(_ns6__WUSchedule *ns6__WUSchedule, _ns6__WUScheduleResponse *ns6__WUScheduleResponse)
{	struct soap *soap = this;
	struct __ns6__WUSchedule soap_tmp___ns6__WUSchedule;
	const char *soap_action = NULL;
	if (!soap_endpoint)
		soap_endpoint = "http://10.173.84.202:8010/WsWorkunits?ver_=1.25";
	soap_action = "WsWorkunits/WUSchedule?ver_=1.25";
	soap->encodingStyle = NULL;
	soap_tmp___ns6__WUSchedule.ns6__WUSchedule = ns6__WUSchedule;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns6__WUSchedule(soap, &soap_tmp___ns6__WUSchedule);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns6__WUSchedule(soap, &soap_tmp___ns6__WUSchedule, "-ns6:WUSchedule", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns6__WUSchedule(soap, &soap_tmp___ns6__WUSchedule, "-ns6:WUSchedule", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns6__WUScheduleResponse)
		return soap_closesock(soap);
	ns6__WUScheduleResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns6__WUScheduleResponse->soap_get(soap, "ns6:WUScheduleResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int WsWorkunitsServiceSoapProxy::WUShowScheduled(_ns6__WUShowScheduled *ns6__WUShowScheduled, _ns6__WUShowScheduledResponse *ns6__WUShowScheduledResponse)
{	struct soap *soap = this;
	struct __ns6__WUShowScheduled soap_tmp___ns6__WUShowScheduled;
	const char *soap_action = NULL;
	if (!soap_endpoint)
		soap_endpoint = "http://10.173.84.202:8010/WsWorkunits?ver_=1.25";
	soap_action = "WsWorkunits/WUShowScheduled?ver_=1.25";
	soap->encodingStyle = NULL;
	soap_tmp___ns6__WUShowScheduled.ns6__WUShowScheduled = ns6__WUShowScheduled;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns6__WUShowScheduled(soap, &soap_tmp___ns6__WUShowScheduled);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns6__WUShowScheduled(soap, &soap_tmp___ns6__WUShowScheduled, "-ns6:WUShowScheduled", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns6__WUShowScheduled(soap, &soap_tmp___ns6__WUShowScheduled, "-ns6:WUShowScheduled", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns6__WUShowScheduledResponse)
		return soap_closesock(soap);
	ns6__WUShowScheduledResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns6__WUShowScheduledResponse->soap_get(soap, "ns6:WUShowScheduledResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int WsWorkunitsServiceSoapProxy::WUSubmit(_ns6__WUSubmit *ns6__WUSubmit, _ns6__WUSubmitResponse *ns6__WUSubmitResponse)
{	struct soap *soap = this;
	struct __ns6__WUSubmit soap_tmp___ns6__WUSubmit;
	const char *soap_action = NULL;
	if (!soap_endpoint)
		soap_endpoint = "http://10.173.84.202:8010/WsWorkunits?ver_=1.25";
	soap_action = "WsWorkunits/WUSubmit?ver_=1.25";
	soap->encodingStyle = NULL;
	soap_tmp___ns6__WUSubmit.ns6__WUSubmit = ns6__WUSubmit;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns6__WUSubmit(soap, &soap_tmp___ns6__WUSubmit);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns6__WUSubmit(soap, &soap_tmp___ns6__WUSubmit, "-ns6:WUSubmit", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns6__WUSubmit(soap, &soap_tmp___ns6__WUSubmit, "-ns6:WUSubmit", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns6__WUSubmitResponse)
		return soap_closesock(soap);
	ns6__WUSubmitResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns6__WUSubmitResponse->soap_get(soap, "ns6:WUSubmitResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int WsWorkunitsServiceSoapProxy::WUSyntaxCheckECL(_ns6__WUSyntaxCheckECL *ns6__WUSyntaxCheckECL, _ns6__WUSyntaxCheckResponse *ns6__WUSyntaxCheckResponse)
{	struct soap *soap = this;
	struct __ns6__WUSyntaxCheckECL soap_tmp___ns6__WUSyntaxCheckECL;
	const char *soap_action = NULL;
	if (!soap_endpoint)
		soap_endpoint = "http://10.173.84.202:8010/WsWorkunits?ver_=1.25";
	soap_action = "WsWorkunits/WUSyntaxCheckECL?ver_=1.25";
	soap->encodingStyle = NULL;
	soap_tmp___ns6__WUSyntaxCheckECL.ns6__WUSyntaxCheckECL = ns6__WUSyntaxCheckECL;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns6__WUSyntaxCheckECL(soap, &soap_tmp___ns6__WUSyntaxCheckECL);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns6__WUSyntaxCheckECL(soap, &soap_tmp___ns6__WUSyntaxCheckECL, "-ns6:WUSyntaxCheckECL", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns6__WUSyntaxCheckECL(soap, &soap_tmp___ns6__WUSyntaxCheckECL, "-ns6:WUSyntaxCheckECL", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns6__WUSyntaxCheckResponse)
		return soap_closesock(soap);
	ns6__WUSyntaxCheckResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns6__WUSyntaxCheckResponse->soap_get(soap, "ns6:WUSyntaxCheckResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int WsWorkunitsServiceSoapProxy::WUUpdate(_ns6__WUUpdate *ns6__WUUpdate, _ns6__WUUpdateResponse *ns6__WUUpdateResponse)
{	struct soap *soap = this;
	struct __ns6__WUUpdate soap_tmp___ns6__WUUpdate;
	const char *soap_action = NULL;
	if (!soap_endpoint)
		soap_endpoint = "http://10.173.84.202:8010/WsWorkunits?ver_=1.25";
	soap_action = "WsWorkunits/WUUpdate?ver_=1.25";
	soap->encodingStyle = NULL;
	soap_tmp___ns6__WUUpdate.ns6__WUUpdate = ns6__WUUpdate;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns6__WUUpdate(soap, &soap_tmp___ns6__WUUpdate);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns6__WUUpdate(soap, &soap_tmp___ns6__WUUpdate, "-ns6:WUUpdate", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns6__WUUpdate(soap, &soap_tmp___ns6__WUUpdate, "-ns6:WUUpdate", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns6__WUUpdateResponse)
		return soap_closesock(soap);
	ns6__WUUpdateResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns6__WUUpdateResponse->soap_get(soap, "ns6:WUUpdateResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int WsWorkunitsServiceSoapProxy::WUWaitCompiled(_ns6__WUWaitCompiled *ns6__WUWaitCompiled, _ns6__WUWaitResponse *ns6__WUWaitResponse)
{	struct soap *soap = this;
	struct __ns6__WUWaitCompiled soap_tmp___ns6__WUWaitCompiled;
	const char *soap_action = NULL;
	if (!soap_endpoint)
		soap_endpoint = "http://10.173.84.202:8010/WsWorkunits?ver_=1.25";
	soap_action = "WsWorkunits/WUWaitCompiled?ver_=1.25";
	soap->encodingStyle = NULL;
	soap_tmp___ns6__WUWaitCompiled.ns6__WUWaitCompiled = ns6__WUWaitCompiled;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns6__WUWaitCompiled(soap, &soap_tmp___ns6__WUWaitCompiled);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns6__WUWaitCompiled(soap, &soap_tmp___ns6__WUWaitCompiled, "-ns6:WUWaitCompiled", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns6__WUWaitCompiled(soap, &soap_tmp___ns6__WUWaitCompiled, "-ns6:WUWaitCompiled", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns6__WUWaitResponse)
		return soap_closesock(soap);
	ns6__WUWaitResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns6__WUWaitResponse->soap_get(soap, "ns6:WUWaitResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int WsWorkunitsServiceSoapProxy::WUWaitComplete(_ns6__WUWaitComplete *ns6__WUWaitComplete, _ns6__WUWaitResponse *ns6__WUWaitResponse)
{	struct soap *soap = this;
	struct __ns6__WUWaitComplete soap_tmp___ns6__WUWaitComplete;
	const char *soap_action = NULL;
	if (!soap_endpoint)
		soap_endpoint = "http://10.173.84.202:8010/WsWorkunits?ver_=1.25";
	soap_action = "WsWorkunits/WUWaitComplete?ver_=1.25";
	soap->encodingStyle = NULL;
	soap_tmp___ns6__WUWaitComplete.ns6__WUWaitComplete = ns6__WUWaitComplete;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns6__WUWaitComplete(soap, &soap_tmp___ns6__WUWaitComplete);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns6__WUWaitComplete(soap, &soap_tmp___ns6__WUWaitComplete, "-ns6:WUWaitComplete", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns6__WUWaitComplete(soap, &soap_tmp___ns6__WUWaitComplete, "-ns6:WUWaitComplete", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns6__WUWaitResponse)
		return soap_closesock(soap);
	ns6__WUWaitResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns6__WUWaitResponse->soap_get(soap, "ns6:WUWaitResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}
/* End of client proxy code */
