/* soapWsAttributesServiceSoapProxy.h
   Generated by gSOAP 2.7.15 from Services.h
   Copyright(C) 2000-2009, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef soapWsAttributesServiceSoapProxy_H
#define soapWsAttributesServiceSoapProxy_H
#include "soapH.h"

class SOAP_CMAC WsAttributesServiceSoapProxy : public soap
{ public:
	/// Endpoint URL of service 'WsAttributesServiceSoapProxy' (change as needed)
	const char *soap_endpoint;
	/// Constructor
	WsAttributesServiceSoapProxy();
	/// Constructor with copy of another engine state
	WsAttributesServiceSoapProxy(const struct soap&);
	/// Constructor with engine input+output mode control
	WsAttributesServiceSoapProxy(soap_mode iomode);
	/// Constructor with engine input and output mode control
	WsAttributesServiceSoapProxy(soap_mode imode, soap_mode omode);
	/// Destructor frees deserialized data
	virtual	~WsAttributesServiceSoapProxy();
	/// Initializer used by constructors
	virtual	void WsAttributesServiceSoapProxy_init(soap_mode imode, soap_mode omode);
	/// Delete all deserialized data (uses soap_destroy and soap_end)
	virtual	void destroy();
	/// Disables and removes SOAP Header from message
	virtual	void soap_noheader();
	/// Get SOAP Fault structure (NULL when absent)
	virtual	const SOAP_ENV__Fault *soap_fault();
	/// Get SOAP Fault string (NULL when absent)
	virtual	const char *soap_fault_string();
	/// Get SOAP Fault detail as string (NULL when absent)
	virtual	const char *soap_fault_detail();
	/// Force close connection (normally automatic, except for send_X ops)
	virtual	int soap_close_socket();
	/// Print fault
	virtual	void soap_print_fault(FILE*);
#ifndef WITH_LEAN
	/// Print fault to stream
	virtual	void soap_stream_fault(std::ostream&);
	/// Put fault into buffer
	virtual	char *soap_sprint_fault(char *buf, size_t len);
#endif

	/// Web service operation 'CheckinAttributes' (returns error code or SOAP_OK)
	virtual	int CheckinAttributes(_ns2__CheckinAttributes *ns2__CheckinAttributes, _ns2__UpdateAttributesResponse *ns2__UpdateAttributesResponse);

	/// Web service operation 'CheckoutAttributes' (returns error code or SOAP_OK)
	virtual	int CheckoutAttributes(_ns2__CheckoutAttributes *ns2__CheckoutAttributes, _ns2__UpdateAttributesResponse *ns2__UpdateAttributesResponse);

	/// Web service operation 'CreateAttribute' (returns error code or SOAP_OK)
	virtual	int CreateAttribute(_ns2__CreateAttribute *ns2__CreateAttribute, _ns2__CreateAttributeResponse *ns2__CreateAttributeResponse);

	/// Web service operation 'CreateLabel' (returns error code or SOAP_OK)
	virtual	int CreateLabel(_ns2__CreateLabel *ns2__CreateLabel, _ns2__CreateLabelResponse *ns2__CreateLabelResponse);

	/// Web service operation 'CreateModule' (returns error code or SOAP_OK)
	virtual	int CreateModule(_ns2__CreateModule *ns2__CreateModule, _ns2__CreateModuleResponse *ns2__CreateModuleResponse);

	/// Web service operation 'DeleteAttributes' (returns error code or SOAP_OK)
	virtual	int DeleteAttributes(_ns2__DeleteAttributes *ns2__DeleteAttributes, _ns2__UpdateAttributesResponse *ns2__UpdateAttributesResponse);

	/// Web service operation 'DeleteLabel' (returns error code or SOAP_OK)
	virtual	int DeleteLabel(_ns2__DeleteLabel *ns2__DeleteLabel, _ns2__DeleteLabelResponse *ns2__DeleteLabelResponse);

	/// Web service operation 'DeleteModule' (returns error code or SOAP_OK)
	virtual	int DeleteModule(_ns2__DeleteModule *ns2__DeleteModule, _ns2__DeleteModuleResponse *ns2__DeleteModuleResponse);

	/// Web service operation 'FindAttributes' (returns error code or SOAP_OK)
	virtual	int FindAttributes(_ns2__FindAttributes *ns2__FindAttributes, _ns2__FindAttributesResponse *ns2__FindAttributesResponse);

	/// Web service operation 'GetAttribute' (returns error code or SOAP_OK)
	virtual	int GetAttribute(_ns2__GetAttribute *ns2__GetAttribute, _ns2__GetAttributeResponse *ns2__GetAttributeResponse);

	/// Web service operation 'GetAttributeHistory' (returns error code or SOAP_OK)
	virtual	int GetAttributeHistory(_ns2__GetAttributeHistory *ns2__GetAttributeHistory, _ns2__GetAttributeHistoryResponse *ns2__GetAttributeHistoryResponse);

	/// Web service operation 'GetAttributeLabels' (returns error code or SOAP_OK)
	virtual	int GetAttributeLabels(_ns2__GetAttributeLabels *ns2__GetAttributeLabels, _ns2__GetAttributeLabelsResponse *ns2__GetAttributeLabelsResponse);

	/// Web service operation 'GetAttributes' (returns error code or SOAP_OK)
	virtual	int GetAttributes(_ns2__GetAttributes *ns2__GetAttributes, _ns2__GetAttributesResponse *ns2__GetAttributesResponse);

	/// Web service operation 'GetLabels' (returns error code or SOAP_OK)
	virtual	int GetLabels(_ns2__GetLabels *ns2__GetLabels, _ns2__GetLabelsResponse *ns2__GetLabelsResponse);

	/// Web service operation 'GetModules' (returns error code or SOAP_OK)
	virtual	int GetModules(_ns2__GetModules *ns2__GetModules, _ns2__GetModulesResponse *ns2__GetModulesResponse);

	/// Web service operation 'ImportAttributes' (returns error code or SOAP_OK)
	virtual	int ImportAttributes(_ns2__ImportAttributes *ns2__ImportAttributes, _ns2__UpdateAttributesResponse *ns2__UpdateAttributesResponse);

	/// Web service operation 'ListAttributeTypes' (returns error code or SOAP_OK)
	virtual	int ListAttributeTypes(_ns2__ListAttributeTypes *ns2__ListAttributeTypes, _ns2__ListAttributeTypesResponse *ns2__ListAttributeTypesResponse);

	/// Web service operation 'RenameAttributes' (returns error code or SOAP_OK)
	virtual	int RenameAttributes(_ns2__RenameAttributes *ns2__RenameAttributes, _ns2__UpdateAttributesResponse *ns2__UpdateAttributesResponse);

	/// Web service operation 'RenameModule' (returns error code or SOAP_OK)
	virtual	int RenameModule(_ns2__RenameModule *ns2__RenameModule, _ns2__RenameModuleResponse *ns2__RenameModuleResponse);

	/// Web service operation 'RollbackAttributes' (returns error code or SOAP_OK)
	virtual	int RollbackAttributes(_ns2__RollbackAttributes *ns2__RollbackAttributes, _ns2__UpdateAttributesResponse *ns2__UpdateAttributesResponse);

	/// Web service operation 'SaveAttributes' (returns error code or SOAP_OK)
	virtual	int SaveAttributes(_ns2__SaveAttributes *ns2__SaveAttributes, _ns2__UpdateAttributesResponse *ns2__UpdateAttributesResponse);

	/// Web service operation 'SupportsEarMark' (returns error code or SOAP_OK)
	virtual	int SupportsEarMark(_ns2__SupportsEarMark *ns2__SupportsEarMark, _ns2__SupportsEarMarkResponse *ns2__SupportsEarMarkResponse);

	/// Web service operation 'UpdateLabel' (returns error code or SOAP_OK)
	virtual	int UpdateLabel(_ns2__UpdateLabel *ns2__UpdateLabel, _ns2__UpdateLabelResponse *ns2__UpdateLabelResponse);
};
#endif
