/* soapWsAttributesServiceSoapProxy.cpp
   Generated by gSOAP 2.7.15 from Services.h
   Copyright(C) 2000-2009, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#include "soapWsAttributesServiceSoapProxy.h"

WsAttributesServiceSoapProxy::WsAttributesServiceSoapProxy()
{	WsAttributesServiceSoapProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
}

WsAttributesServiceSoapProxy::WsAttributesServiceSoapProxy(const struct soap &_soap) :soap(_soap)
{ }

WsAttributesServiceSoapProxy::WsAttributesServiceSoapProxy(soap_mode iomode)
{	WsAttributesServiceSoapProxy_init(iomode, iomode);
}

WsAttributesServiceSoapProxy::WsAttributesServiceSoapProxy(soap_mode imode, soap_mode omode)
{	WsAttributesServiceSoapProxy_init(imode, omode);
}

void WsAttributesServiceSoapProxy::WsAttributesServiceSoapProxy_init(soap_mode imode, soap_mode omode)
{	soap_imode(this, imode);
	soap_omode(this, omode);
	soap_endpoint = NULL;
	static const struct Namespace namespaces[] =
{
	{"SOAP-ENV", "http://schemas.xmlsoap.org/soap/envelope/", "http://www.w3.org/*/soap-envelope", NULL},
	{"SOAP-ENC", "http://schemas.xmlsoap.org/soap/encoding/", "http://www.w3.org/*/soap-encoding", NULL},
	{"xsi", "http://www.w3.org/2001/XMLSchema-instance", "http://www.w3.org/*/XMLSchema-instance", NULL},
	{"xsd", "http://www.w3.org/2001/XMLSchema", "http://www.w3.org/*/XMLSchema", NULL},
	{"ns1", "http://webservices.seisint.com/ws_account", NULL, NULL},
	{"ns2", "urn:hpccsystems:ws:wsattributes", NULL, NULL},
	{"ns3", "urn:hpccsystems:ws:wsdfu", NULL, NULL},
	{"ns4", "urn:hpccsystems:ws:wssmc", NULL, NULL},
	{"ns5", "http://webservices.seisint.com/WsTopology", NULL, NULL},
	{"ns6", "urn:hpccsystems:ws:wsworkunits", NULL, NULL},
	{NULL, NULL, NULL, NULL}
};
	if (!this->namespaces)
		this->namespaces = namespaces;
}

WsAttributesServiceSoapProxy::~WsAttributesServiceSoapProxy()
{ }

void WsAttributesServiceSoapProxy::destroy()
{	soap_destroy(this);
	soap_end(this);
}

void WsAttributesServiceSoapProxy::soap_noheader()
{	header = NULL;
}

const SOAP_ENV__Fault *WsAttributesServiceSoapProxy::soap_fault()
{	return this->fault;
}

const char *WsAttributesServiceSoapProxy::soap_fault_string()
{	return *soap_faultstring(this);
}

const char *WsAttributesServiceSoapProxy::soap_fault_detail()
{	return *soap_faultdetail(this);
}

int WsAttributesServiceSoapProxy::soap_close_socket()
{	return soap_closesock(this);
}

void WsAttributesServiceSoapProxy::soap_print_fault(FILE *fd)
{	::soap_print_fault(this, fd);
}

#ifndef WITH_LEAN
void WsAttributesServiceSoapProxy::soap_stream_fault(std::ostream& os)
{	::soap_stream_fault(this, os);
}

char *WsAttributesServiceSoapProxy::soap_sprint_fault(char *buf, size_t len)
{	return ::soap_sprint_fault(this, buf, len);
}
#endif

int WsAttributesServiceSoapProxy::CheckinAttributes(_ns2__CheckinAttributes *ns2__CheckinAttributes, _ns2__UpdateAttributesResponse *ns2__UpdateAttributesResponse)
{	struct soap *soap = this;
	struct __ns2__CheckinAttributes soap_tmp___ns2__CheckinAttributes;
	const char *soap_action = NULL;
	if (!soap_endpoint)
		soap_endpoint = "http://10.241.3.241:8145/WsAttributes?ver_=1.21";
	soap_action = "WsAttributes/CheckinAttributes?ver_=1.21";
	soap->encodingStyle = NULL;
	soap_tmp___ns2__CheckinAttributes.ns2__CheckinAttributes = ns2__CheckinAttributes;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns2__CheckinAttributes(soap, &soap_tmp___ns2__CheckinAttributes);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns2__CheckinAttributes(soap, &soap_tmp___ns2__CheckinAttributes, "-ns2:CheckinAttributes", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns2__CheckinAttributes(soap, &soap_tmp___ns2__CheckinAttributes, "-ns2:CheckinAttributes", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns2__UpdateAttributesResponse)
		return soap_closesock(soap);
	ns2__UpdateAttributesResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns2__UpdateAttributesResponse->soap_get(soap, "ns2:UpdateAttributesResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int WsAttributesServiceSoapProxy::CheckoutAttributes(_ns2__CheckoutAttributes *ns2__CheckoutAttributes, _ns2__UpdateAttributesResponse *ns2__UpdateAttributesResponse)
{	struct soap *soap = this;
	struct __ns2__CheckoutAttributes soap_tmp___ns2__CheckoutAttributes;
	const char *soap_action = NULL;
	if (!soap_endpoint)
		soap_endpoint = "http://10.241.3.241:8145/WsAttributes?ver_=1.21";
	soap_action = "WsAttributes/CheckoutAttributes?ver_=1.21";
	soap->encodingStyle = NULL;
	soap_tmp___ns2__CheckoutAttributes.ns2__CheckoutAttributes = ns2__CheckoutAttributes;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns2__CheckoutAttributes(soap, &soap_tmp___ns2__CheckoutAttributes);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns2__CheckoutAttributes(soap, &soap_tmp___ns2__CheckoutAttributes, "-ns2:CheckoutAttributes", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns2__CheckoutAttributes(soap, &soap_tmp___ns2__CheckoutAttributes, "-ns2:CheckoutAttributes", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns2__UpdateAttributesResponse)
		return soap_closesock(soap);
	ns2__UpdateAttributesResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns2__UpdateAttributesResponse->soap_get(soap, "ns2:UpdateAttributesResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int WsAttributesServiceSoapProxy::CreateAttribute(_ns2__CreateAttribute *ns2__CreateAttribute, _ns2__CreateAttributeResponse *ns2__CreateAttributeResponse)
{	struct soap *soap = this;
	struct __ns2__CreateAttribute soap_tmp___ns2__CreateAttribute;
	const char *soap_action = NULL;
	if (!soap_endpoint)
		soap_endpoint = "http://10.241.3.241:8145/WsAttributes?ver_=1.21";
	soap_action = "WsAttributes/CreateAttribute?ver_=1.21";
	soap->encodingStyle = NULL;
	soap_tmp___ns2__CreateAttribute.ns2__CreateAttribute = ns2__CreateAttribute;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns2__CreateAttribute(soap, &soap_tmp___ns2__CreateAttribute);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns2__CreateAttribute(soap, &soap_tmp___ns2__CreateAttribute, "-ns2:CreateAttribute", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns2__CreateAttribute(soap, &soap_tmp___ns2__CreateAttribute, "-ns2:CreateAttribute", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns2__CreateAttributeResponse)
		return soap_closesock(soap);
	ns2__CreateAttributeResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns2__CreateAttributeResponse->soap_get(soap, "ns2:CreateAttributeResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int WsAttributesServiceSoapProxy::CreateLabel(_ns2__CreateLabel *ns2__CreateLabel, _ns2__CreateLabelResponse *ns2__CreateLabelResponse)
{	struct soap *soap = this;
	struct __ns2__CreateLabel soap_tmp___ns2__CreateLabel;
	const char *soap_action = NULL;
	if (!soap_endpoint)
		soap_endpoint = "http://10.241.3.241:8145/WsAttributes?ver_=1.21";
	soap_action = "WsAttributes/CreateLabel?ver_=1.21";
	soap->encodingStyle = NULL;
	soap_tmp___ns2__CreateLabel.ns2__CreateLabel = ns2__CreateLabel;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns2__CreateLabel(soap, &soap_tmp___ns2__CreateLabel);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns2__CreateLabel(soap, &soap_tmp___ns2__CreateLabel, "-ns2:CreateLabel", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns2__CreateLabel(soap, &soap_tmp___ns2__CreateLabel, "-ns2:CreateLabel", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns2__CreateLabelResponse)
		return soap_closesock(soap);
	ns2__CreateLabelResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns2__CreateLabelResponse->soap_get(soap, "ns2:CreateLabelResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int WsAttributesServiceSoapProxy::CreateModule(_ns2__CreateModule *ns2__CreateModule, _ns2__CreateModuleResponse *ns2__CreateModuleResponse)
{	struct soap *soap = this;
	struct __ns2__CreateModule soap_tmp___ns2__CreateModule;
	const char *soap_action = NULL;
	if (!soap_endpoint)
		soap_endpoint = "http://10.241.3.241:8145/WsAttributes?ver_=1.21";
	soap_action = "WsAttributes/CreateModule?ver_=1.21";
	soap->encodingStyle = NULL;
	soap_tmp___ns2__CreateModule.ns2__CreateModule = ns2__CreateModule;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns2__CreateModule(soap, &soap_tmp___ns2__CreateModule);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns2__CreateModule(soap, &soap_tmp___ns2__CreateModule, "-ns2:CreateModule", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns2__CreateModule(soap, &soap_tmp___ns2__CreateModule, "-ns2:CreateModule", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns2__CreateModuleResponse)
		return soap_closesock(soap);
	ns2__CreateModuleResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns2__CreateModuleResponse->soap_get(soap, "ns2:CreateModuleResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int WsAttributesServiceSoapProxy::DeleteAttributes(_ns2__DeleteAttributes *ns2__DeleteAttributes, _ns2__UpdateAttributesResponse *ns2__UpdateAttributesResponse)
{	struct soap *soap = this;
	struct __ns2__DeleteAttributes soap_tmp___ns2__DeleteAttributes;
	const char *soap_action = NULL;
	if (!soap_endpoint)
		soap_endpoint = "http://10.241.3.241:8145/WsAttributes?ver_=1.21";
	soap_action = "WsAttributes/DeleteAttributes?ver_=1.21";
	soap->encodingStyle = NULL;
	soap_tmp___ns2__DeleteAttributes.ns2__DeleteAttributes = ns2__DeleteAttributes;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns2__DeleteAttributes(soap, &soap_tmp___ns2__DeleteAttributes);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns2__DeleteAttributes(soap, &soap_tmp___ns2__DeleteAttributes, "-ns2:DeleteAttributes", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns2__DeleteAttributes(soap, &soap_tmp___ns2__DeleteAttributes, "-ns2:DeleteAttributes", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns2__UpdateAttributesResponse)
		return soap_closesock(soap);
	ns2__UpdateAttributesResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns2__UpdateAttributesResponse->soap_get(soap, "ns2:UpdateAttributesResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int WsAttributesServiceSoapProxy::DeleteLabel(_ns2__DeleteLabel *ns2__DeleteLabel, _ns2__DeleteLabelResponse *ns2__DeleteLabelResponse)
{	struct soap *soap = this;
	struct __ns2__DeleteLabel soap_tmp___ns2__DeleteLabel;
	const char *soap_action = NULL;
	if (!soap_endpoint)
		soap_endpoint = "http://10.241.3.241:8145/WsAttributes?ver_=1.21";
	soap_action = "WsAttributes/DeleteLabel?ver_=1.21";
	soap->encodingStyle = NULL;
	soap_tmp___ns2__DeleteLabel.ns2__DeleteLabel = ns2__DeleteLabel;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns2__DeleteLabel(soap, &soap_tmp___ns2__DeleteLabel);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns2__DeleteLabel(soap, &soap_tmp___ns2__DeleteLabel, "-ns2:DeleteLabel", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns2__DeleteLabel(soap, &soap_tmp___ns2__DeleteLabel, "-ns2:DeleteLabel", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns2__DeleteLabelResponse)
		return soap_closesock(soap);
	ns2__DeleteLabelResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns2__DeleteLabelResponse->soap_get(soap, "ns2:DeleteLabelResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int WsAttributesServiceSoapProxy::DeleteModule(_ns2__DeleteModule *ns2__DeleteModule, _ns2__DeleteModuleResponse *ns2__DeleteModuleResponse)
{	struct soap *soap = this;
	struct __ns2__DeleteModule soap_tmp___ns2__DeleteModule;
	const char *soap_action = NULL;
	if (!soap_endpoint)
		soap_endpoint = "http://10.241.3.241:8145/WsAttributes?ver_=1.21";
	soap_action = "WsAttributes/DeleteModule?ver_=1.21";
	soap->encodingStyle = NULL;
	soap_tmp___ns2__DeleteModule.ns2__DeleteModule = ns2__DeleteModule;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns2__DeleteModule(soap, &soap_tmp___ns2__DeleteModule);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns2__DeleteModule(soap, &soap_tmp___ns2__DeleteModule, "-ns2:DeleteModule", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns2__DeleteModule(soap, &soap_tmp___ns2__DeleteModule, "-ns2:DeleteModule", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns2__DeleteModuleResponse)
		return soap_closesock(soap);
	ns2__DeleteModuleResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns2__DeleteModuleResponse->soap_get(soap, "ns2:DeleteModuleResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int WsAttributesServiceSoapProxy::FindAttributes(_ns2__FindAttributes *ns2__FindAttributes, _ns2__FindAttributesResponse *ns2__FindAttributesResponse)
{	struct soap *soap = this;
	struct __ns2__FindAttributes soap_tmp___ns2__FindAttributes;
	const char *soap_action = NULL;
	if (!soap_endpoint)
		soap_endpoint = "http://10.241.3.241:8145/WsAttributes?ver_=1.21";
	soap_action = "WsAttributes/FindAttributes?ver_=1.21";
	soap->encodingStyle = NULL;
	soap_tmp___ns2__FindAttributes.ns2__FindAttributes = ns2__FindAttributes;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns2__FindAttributes(soap, &soap_tmp___ns2__FindAttributes);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns2__FindAttributes(soap, &soap_tmp___ns2__FindAttributes, "-ns2:FindAttributes", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns2__FindAttributes(soap, &soap_tmp___ns2__FindAttributes, "-ns2:FindAttributes", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns2__FindAttributesResponse)
		return soap_closesock(soap);
	ns2__FindAttributesResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns2__FindAttributesResponse->soap_get(soap, "ns2:FindAttributesResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int WsAttributesServiceSoapProxy::GetAttribute(_ns2__GetAttribute *ns2__GetAttribute, _ns2__GetAttributeResponse *ns2__GetAttributeResponse)
{	struct soap *soap = this;
	struct __ns2__GetAttribute soap_tmp___ns2__GetAttribute;
	const char *soap_action = NULL;
	if (!soap_endpoint)
		soap_endpoint = "http://10.241.3.241:8145/WsAttributes?ver_=1.21";
	soap_action = "WsAttributes/GetAttribute?ver_=1.21";
	soap->encodingStyle = NULL;
	soap_tmp___ns2__GetAttribute.ns2__GetAttribute = ns2__GetAttribute;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns2__GetAttribute(soap, &soap_tmp___ns2__GetAttribute);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns2__GetAttribute(soap, &soap_tmp___ns2__GetAttribute, "-ns2:GetAttribute", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns2__GetAttribute(soap, &soap_tmp___ns2__GetAttribute, "-ns2:GetAttribute", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns2__GetAttributeResponse)
		return soap_closesock(soap);
	ns2__GetAttributeResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns2__GetAttributeResponse->soap_get(soap, "ns2:GetAttributeResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int WsAttributesServiceSoapProxy::GetAttributeHistory(_ns2__GetAttributeHistory *ns2__GetAttributeHistory, _ns2__GetAttributeHistoryResponse *ns2__GetAttributeHistoryResponse)
{	struct soap *soap = this;
	struct __ns2__GetAttributeHistory soap_tmp___ns2__GetAttributeHistory;
	const char *soap_action = NULL;
	if (!soap_endpoint)
		soap_endpoint = "http://10.241.3.241:8145/WsAttributes?ver_=1.21";
	soap_action = "WsAttributes/GetAttributeHistory?ver_=1.21";
	soap->encodingStyle = NULL;
	soap_tmp___ns2__GetAttributeHistory.ns2__GetAttributeHistory = ns2__GetAttributeHistory;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns2__GetAttributeHistory(soap, &soap_tmp___ns2__GetAttributeHistory);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns2__GetAttributeHistory(soap, &soap_tmp___ns2__GetAttributeHistory, "-ns2:GetAttributeHistory", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns2__GetAttributeHistory(soap, &soap_tmp___ns2__GetAttributeHistory, "-ns2:GetAttributeHistory", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns2__GetAttributeHistoryResponse)
		return soap_closesock(soap);
	ns2__GetAttributeHistoryResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns2__GetAttributeHistoryResponse->soap_get(soap, "ns2:GetAttributeHistoryResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int WsAttributesServiceSoapProxy::GetAttributeLabels(_ns2__GetAttributeLabels *ns2__GetAttributeLabels, _ns2__GetAttributeLabelsResponse *ns2__GetAttributeLabelsResponse)
{	struct soap *soap = this;
	struct __ns2__GetAttributeLabels soap_tmp___ns2__GetAttributeLabels;
	const char *soap_action = NULL;
	if (!soap_endpoint)
		soap_endpoint = "http://10.241.3.241:8145/WsAttributes?ver_=1.21";
	soap_action = "WsAttributes/GetAttributeLabels?ver_=1.21";
	soap->encodingStyle = NULL;
	soap_tmp___ns2__GetAttributeLabels.ns2__GetAttributeLabels = ns2__GetAttributeLabels;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns2__GetAttributeLabels(soap, &soap_tmp___ns2__GetAttributeLabels);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns2__GetAttributeLabels(soap, &soap_tmp___ns2__GetAttributeLabels, "-ns2:GetAttributeLabels", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns2__GetAttributeLabels(soap, &soap_tmp___ns2__GetAttributeLabels, "-ns2:GetAttributeLabels", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns2__GetAttributeLabelsResponse)
		return soap_closesock(soap);
	ns2__GetAttributeLabelsResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns2__GetAttributeLabelsResponse->soap_get(soap, "ns2:GetAttributeLabelsResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int WsAttributesServiceSoapProxy::GetAttributes(_ns2__GetAttributes *ns2__GetAttributes, _ns2__GetAttributesResponse *ns2__GetAttributesResponse)
{	struct soap *soap = this;
	struct __ns2__GetAttributes soap_tmp___ns2__GetAttributes;
	const char *soap_action = NULL;
	if (!soap_endpoint)
		soap_endpoint = "http://10.241.3.241:8145/WsAttributes?ver_=1.21";
	soap_action = "WsAttributes/GetAttributes?ver_=1.21";
	soap->encodingStyle = NULL;
	soap_tmp___ns2__GetAttributes.ns2__GetAttributes = ns2__GetAttributes;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns2__GetAttributes(soap, &soap_tmp___ns2__GetAttributes);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns2__GetAttributes(soap, &soap_tmp___ns2__GetAttributes, "-ns2:GetAttributes", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns2__GetAttributes(soap, &soap_tmp___ns2__GetAttributes, "-ns2:GetAttributes", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns2__GetAttributesResponse)
		return soap_closesock(soap);
	ns2__GetAttributesResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns2__GetAttributesResponse->soap_get(soap, "ns2:GetAttributesResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int WsAttributesServiceSoapProxy::GetLabels(_ns2__GetLabels *ns2__GetLabels, _ns2__GetLabelsResponse *ns2__GetLabelsResponse)
{	struct soap *soap = this;
	struct __ns2__GetLabels soap_tmp___ns2__GetLabels;
	const char *soap_action = NULL;
	if (!soap_endpoint)
		soap_endpoint = "http://10.241.3.241:8145/WsAttributes?ver_=1.21";
	soap_action = "WsAttributes/GetLabels?ver_=1.21";
	soap->encodingStyle = NULL;
	soap_tmp___ns2__GetLabels.ns2__GetLabels = ns2__GetLabels;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns2__GetLabels(soap, &soap_tmp___ns2__GetLabels);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns2__GetLabels(soap, &soap_tmp___ns2__GetLabels, "-ns2:GetLabels", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns2__GetLabels(soap, &soap_tmp___ns2__GetLabels, "-ns2:GetLabels", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns2__GetLabelsResponse)
		return soap_closesock(soap);
	ns2__GetLabelsResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns2__GetLabelsResponse->soap_get(soap, "ns2:GetLabelsResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int WsAttributesServiceSoapProxy::GetModules(_ns2__GetModules *ns2__GetModules, _ns2__GetModulesResponse *ns2__GetModulesResponse)
{	struct soap *soap = this;
	struct __ns2__GetModules soap_tmp___ns2__GetModules;
	const char *soap_action = NULL;
	if (!soap_endpoint)
		soap_endpoint = "http://10.241.3.241:8145/WsAttributes?ver_=1.21";
	soap_action = "WsAttributes/GetModules?ver_=1.21";
	soap->encodingStyle = NULL;
	soap_tmp___ns2__GetModules.ns2__GetModules = ns2__GetModules;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns2__GetModules(soap, &soap_tmp___ns2__GetModules);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns2__GetModules(soap, &soap_tmp___ns2__GetModules, "-ns2:GetModules", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns2__GetModules(soap, &soap_tmp___ns2__GetModules, "-ns2:GetModules", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns2__GetModulesResponse)
		return soap_closesock(soap);
	ns2__GetModulesResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns2__GetModulesResponse->soap_get(soap, "ns2:GetModulesResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int WsAttributesServiceSoapProxy::ImportAttributes(_ns2__ImportAttributes *ns2__ImportAttributes, _ns2__UpdateAttributesResponse *ns2__UpdateAttributesResponse)
{	struct soap *soap = this;
	struct __ns2__ImportAttributes soap_tmp___ns2__ImportAttributes;
	const char *soap_action = NULL;
	if (!soap_endpoint)
		soap_endpoint = "http://10.241.3.241:8145/WsAttributes?ver_=1.21";
	soap_action = "WsAttributes/ImportAttributes?ver_=1.21";
	soap->encodingStyle = NULL;
	soap_tmp___ns2__ImportAttributes.ns2__ImportAttributes = ns2__ImportAttributes;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns2__ImportAttributes(soap, &soap_tmp___ns2__ImportAttributes);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns2__ImportAttributes(soap, &soap_tmp___ns2__ImportAttributes, "-ns2:ImportAttributes", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns2__ImportAttributes(soap, &soap_tmp___ns2__ImportAttributes, "-ns2:ImportAttributes", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns2__UpdateAttributesResponse)
		return soap_closesock(soap);
	ns2__UpdateAttributesResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns2__UpdateAttributesResponse->soap_get(soap, "ns2:UpdateAttributesResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int WsAttributesServiceSoapProxy::ListAttributeTypes(_ns2__ListAttributeTypes *ns2__ListAttributeTypes, _ns2__ListAttributeTypesResponse *ns2__ListAttributeTypesResponse)
{	struct soap *soap = this;
	struct __ns2__ListAttributeTypes soap_tmp___ns2__ListAttributeTypes;
	const char *soap_action = NULL;
	if (!soap_endpoint)
		soap_endpoint = "http://10.241.3.241:8145/WsAttributes?ver_=1.21";
	soap_action = "WsAttributes/ListAttributeTypes?ver_=1.21";
	soap->encodingStyle = NULL;
	soap_tmp___ns2__ListAttributeTypes.ns2__ListAttributeTypes = ns2__ListAttributeTypes;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns2__ListAttributeTypes(soap, &soap_tmp___ns2__ListAttributeTypes);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns2__ListAttributeTypes(soap, &soap_tmp___ns2__ListAttributeTypes, "-ns2:ListAttributeTypes", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns2__ListAttributeTypes(soap, &soap_tmp___ns2__ListAttributeTypes, "-ns2:ListAttributeTypes", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns2__ListAttributeTypesResponse)
		return soap_closesock(soap);
	ns2__ListAttributeTypesResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns2__ListAttributeTypesResponse->soap_get(soap, "ns2:ListAttributeTypesResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int WsAttributesServiceSoapProxy::RenameAttributes(_ns2__RenameAttributes *ns2__RenameAttributes, _ns2__UpdateAttributesResponse *ns2__UpdateAttributesResponse)
{	struct soap *soap = this;
	struct __ns2__RenameAttributes soap_tmp___ns2__RenameAttributes;
	const char *soap_action = NULL;
	if (!soap_endpoint)
		soap_endpoint = "http://10.241.3.241:8145/WsAttributes?ver_=1.21";
	soap_action = "WsAttributes/RenameAttributes?ver_=1.21";
	soap->encodingStyle = NULL;
	soap_tmp___ns2__RenameAttributes.ns2__RenameAttributes = ns2__RenameAttributes;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns2__RenameAttributes(soap, &soap_tmp___ns2__RenameAttributes);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns2__RenameAttributes(soap, &soap_tmp___ns2__RenameAttributes, "-ns2:RenameAttributes", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns2__RenameAttributes(soap, &soap_tmp___ns2__RenameAttributes, "-ns2:RenameAttributes", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns2__UpdateAttributesResponse)
		return soap_closesock(soap);
	ns2__UpdateAttributesResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns2__UpdateAttributesResponse->soap_get(soap, "ns2:UpdateAttributesResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int WsAttributesServiceSoapProxy::RenameModule(_ns2__RenameModule *ns2__RenameModule, _ns2__RenameModuleResponse *ns2__RenameModuleResponse)
{	struct soap *soap = this;
	struct __ns2__RenameModule soap_tmp___ns2__RenameModule;
	const char *soap_action = NULL;
	if (!soap_endpoint)
		soap_endpoint = "http://10.241.3.241:8145/WsAttributes?ver_=1.21";
	soap_action = "WsAttributes/RenameModule?ver_=1.21";
	soap->encodingStyle = NULL;
	soap_tmp___ns2__RenameModule.ns2__RenameModule = ns2__RenameModule;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns2__RenameModule(soap, &soap_tmp___ns2__RenameModule);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns2__RenameModule(soap, &soap_tmp___ns2__RenameModule, "-ns2:RenameModule", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns2__RenameModule(soap, &soap_tmp___ns2__RenameModule, "-ns2:RenameModule", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns2__RenameModuleResponse)
		return soap_closesock(soap);
	ns2__RenameModuleResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns2__RenameModuleResponse->soap_get(soap, "ns2:RenameModuleResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int WsAttributesServiceSoapProxy::RollbackAttributes(_ns2__RollbackAttributes *ns2__RollbackAttributes, _ns2__UpdateAttributesResponse *ns2__UpdateAttributesResponse)
{	struct soap *soap = this;
	struct __ns2__RollbackAttributes soap_tmp___ns2__RollbackAttributes;
	const char *soap_action = NULL;
	if (!soap_endpoint)
		soap_endpoint = "http://10.241.3.241:8145/WsAttributes?ver_=1.21";
	soap_action = "WsAttributes/RollbackAttributes?ver_=1.21";
	soap->encodingStyle = NULL;
	soap_tmp___ns2__RollbackAttributes.ns2__RollbackAttributes = ns2__RollbackAttributes;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns2__RollbackAttributes(soap, &soap_tmp___ns2__RollbackAttributes);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns2__RollbackAttributes(soap, &soap_tmp___ns2__RollbackAttributes, "-ns2:RollbackAttributes", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns2__RollbackAttributes(soap, &soap_tmp___ns2__RollbackAttributes, "-ns2:RollbackAttributes", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns2__UpdateAttributesResponse)
		return soap_closesock(soap);
	ns2__UpdateAttributesResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns2__UpdateAttributesResponse->soap_get(soap, "ns2:UpdateAttributesResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int WsAttributesServiceSoapProxy::SaveAttributes(_ns2__SaveAttributes *ns2__SaveAttributes, _ns2__UpdateAttributesResponse *ns2__UpdateAttributesResponse)
{	struct soap *soap = this;
	struct __ns2__SaveAttributes soap_tmp___ns2__SaveAttributes;
	const char *soap_action = NULL;
	if (!soap_endpoint)
		soap_endpoint = "http://10.241.3.241:8145/WsAttributes?ver_=1.21";
	soap_action = "WsAttributes/SaveAttributes?ver_=1.21";
	soap->encodingStyle = NULL;
	soap_tmp___ns2__SaveAttributes.ns2__SaveAttributes = ns2__SaveAttributes;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns2__SaveAttributes(soap, &soap_tmp___ns2__SaveAttributes);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns2__SaveAttributes(soap, &soap_tmp___ns2__SaveAttributes, "-ns2:SaveAttributes", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns2__SaveAttributes(soap, &soap_tmp___ns2__SaveAttributes, "-ns2:SaveAttributes", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns2__UpdateAttributesResponse)
		return soap_closesock(soap);
	ns2__UpdateAttributesResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns2__UpdateAttributesResponse->soap_get(soap, "ns2:UpdateAttributesResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int WsAttributesServiceSoapProxy::SupportsEarMark(_ns2__SupportsEarMark *ns2__SupportsEarMark, _ns2__SupportsEarMarkResponse *ns2__SupportsEarMarkResponse)
{	struct soap *soap = this;
	struct __ns2__SupportsEarMark soap_tmp___ns2__SupportsEarMark;
	const char *soap_action = NULL;
	if (!soap_endpoint)
		soap_endpoint = "http://10.241.3.241:8145/WsAttributes?ver_=1.21";
	soap_action = "WsAttributes/SupportsEarMark?ver_=1.21";
	soap->encodingStyle = NULL;
	soap_tmp___ns2__SupportsEarMark.ns2__SupportsEarMark = ns2__SupportsEarMark;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns2__SupportsEarMark(soap, &soap_tmp___ns2__SupportsEarMark);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns2__SupportsEarMark(soap, &soap_tmp___ns2__SupportsEarMark, "-ns2:SupportsEarMark", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns2__SupportsEarMark(soap, &soap_tmp___ns2__SupportsEarMark, "-ns2:SupportsEarMark", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns2__SupportsEarMarkResponse)
		return soap_closesock(soap);
	ns2__SupportsEarMarkResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns2__SupportsEarMarkResponse->soap_get(soap, "ns2:SupportsEarMarkResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int WsAttributesServiceSoapProxy::UpdateLabel(_ns2__UpdateLabel *ns2__UpdateLabel, _ns2__UpdateLabelResponse *ns2__UpdateLabelResponse)
{	struct soap *soap = this;
	struct __ns2__UpdateLabel soap_tmp___ns2__UpdateLabel;
	const char *soap_action = NULL;
	if (!soap_endpoint)
		soap_endpoint = "http://10.241.3.241:8145/WsAttributes?ver_=1.21";
	soap_action = "WsAttributes/UpdateLabel?ver_=1.21";
	soap->encodingStyle = NULL;
	soap_tmp___ns2__UpdateLabel.ns2__UpdateLabel = ns2__UpdateLabel;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns2__UpdateLabel(soap, &soap_tmp___ns2__UpdateLabel);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns2__UpdateLabel(soap, &soap_tmp___ns2__UpdateLabel, "-ns2:UpdateLabel", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns2__UpdateLabel(soap, &soap_tmp___ns2__UpdateLabel, "-ns2:UpdateLabel", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns2__UpdateLabelResponse)
		return soap_closesock(soap);
	ns2__UpdateLabelResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns2__UpdateLabelResponse->soap_get(soap, "ns2:UpdateLabelResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}
/* End of client proxy code */
